/**
 * SC15 full-vs-blob projection field-by-field deepEqual comparison.
 *
 * The fixture `full-mode-baseline.trace.jsonl` freezes the historical ground truth of
 * full-mode writes (full-mode-baseline.test.ts in this directory already pins its
 * read-side projection field by field). This file writes a **same-content** trace with
 * the **current blob-only write side** (`createJsonlTraceService`, whose full branch is
 * retired), runs the same read-side projection, and asserts the two forms' projected
 * values are field-equal — "projection is insensitive to storage form" is pinned by
 * real dual-form data, not inferred from a one-sided fixture.
 *
 * Conversation content matches the full fixture (4 rows: llm-1 → tool-1 → llm-2 → turn-1);
 * record ids are generated by the write side and read back (recordLlmCall returns the id),
 * no preset deterministic ids — the comparison keys are projected scalar values, not id strings.
 */
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  existsSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, it } from "vitest";
import assert from "node:assert/strict";

import { createJsonlTraceService } from "../../src/harness/trace/jsonl.ts";
import {
  createQueryTraceCore,
  type QueryTraceCoreHandler,
} from "../../src/traceserver/query-trace-core.ts";

const traceDirs: string[] = [];
const TEST_PROJECT_SLUG = "test-project-blob-baseline";

afterEach(() => {
  for (const dir of traceDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

interface Page {
  records: Array<Record<string, unknown>>;
  limit: number;
  offset: number;
}

function queryCoreFor(traceDir: string): QueryTraceCoreHandler {
  return createQueryTraceCore({ traceDir });
}

async function queryPage(
  core: QueryTraceCoreHandler,
  conversationId: string,
  input: Record<string, unknown>
): Promise<Page> {
  return JSON.parse(
    await core({ conversation_id: conversationId, ...input })
  ) as Page;
}

/** Replicate the trace file into the two-level-tree landing spot, keeping the same directory shape as the full fixture. */
function makeTraceDir(): string {
  const traceDir = mkdtempSync(join(tmpdir(), "iknow-blob-baseline-"));
  traceDirs.push(traceDir);
  mkdirSync(join(traceDir, "projects", TEST_PROJECT_SLUG, "baseline-conv"), {
    recursive: true,
  });
  return traceDir;
}

describe("L-sc15 — same-content full-vs-blob projection deepEqual", () => {
  it("blob-only 写侧同内容 trace 的投影与 full fixture 固化值逐字段相等 (SC15)", async () => {
    const traceDir = makeTraceDir();
    const convDir = join(
      traceDir,
      "projects",
      TEST_PROJECT_SLUG,
      "baseline-conv"
    );
    const trace = createJsonlTraceService({
      traceFilePath: join(convDir, "trace.jsonl"),
      conversationId: "baseline-conv",
    });

    // Message array byte-identical to the full fixture (after deref the projections should match exactly).
    const systemMsg = {
      role: "system",
      content: "You are a helpful assistant.",
    };
    const userTextMsg = {
      role: "user",
      content: [{ type: "text", text: "hello world" }],
    };
    const assistantToolUseMsg = {
      role: "assistant",
      content: [
        {
          type: "tool_use",
          id: "toolu-1",
          name: "bash",
          input: { command: "ls" },
        },
      ],
    };
    const userToolResultMsg = {
      role: "user",
      content: [
        {
          type: "tool_result",
          tool_use_id: "toolu-1",
          content: "file-a\nfile-b",
        },
      ],
    };

    const llm1 = await trace.recordLlmCall({
      startedAt: "2026-09-08T00:00:00.000Z",
      endedAt: "2026-09-08T00:00:01.000Z",
      durationMs: 1000,
      // supplier_stop is the *supplier* stop verdict (success|truncation|
      // refusal|other) — the old "tool_use" value is no longer in the domain.
      // A live ok call records "success" (loop-engine fills it that way); the
      // tool-use signal now lives in the separate tool_call record below.
      supplierStop: "success",
      stream: false,
      messagesCaptured: true,
      messages: [systemMsg, userTextMsg],
      status: "ok",
      inputTokens: 120,
      outputTokens: 30,
    });
    const tool1 = await trace.recordToolCall({
      parentLlmCallId: llm1,
      toolName: "bash",
      toolKind: "ok",
      startedAt: "2026-09-08T00:00:01.500Z",
      endedAt: "2026-09-08T00:00:02.000Z",
      durationMs: 500,
      argumentsCaptured: true,
      arguments: { command: "ls" },
      resultCaptured: true,
      result: "file-a\nfile-b",
      status: "ok",
    });
    const llm2 = await trace.recordLlmCall({
      startedAt: "2026-09-08T00:00:02.500Z",
      endedAt: "2026-09-08T00:00:03.500Z",
      durationMs: 1000,
      supplierStop: "success",
      stream: false,
      messagesCaptured: true,
      messages: [
        systemMsg,
        userTextMsg,
        assistantToolUseMsg,
        userToolResultMsg,
      ],
      status: "ok",
      inputTokens: 260,
      outputTokens: 45,
    });
    await trace.recordTurn({
      id: "turn-1",
      turnIndex: 0,
      startedAt: "2026-09-08T00:00:00.000Z",
      endedAt: "2026-09-08T00:00:04.000Z",
      durationMs: 4000,
      llmCallIds: [llm1!, llm2!],
      toolCallIds: [tool1!],
      decision: "completed",
      status: "ok",
    });

    // Blob-form persistence sanity: on the row, messages are {role, content:{sha,bytes}} references,
    // and the blobs/ directory holds at least one entry.
    const lines = readFileSync(join(convDir, "trace.jsonl"), "utf8")
      .trim()
      .split("\n")
      .map((l) => JSON.parse(l) as Record<string, unknown>);
    const blobRow = lines.find(
      (l) => l.record_type === "llm_call" && l.llm_call_id === llm1
    );
    const rawMessages = blobRow?.messages as Array<Record<string, unknown>>;
    assert.ok(Array.isArray(rawMessages), "llm-1 行应有 messages 数组");
    assert.ok(
      rawMessages.every(
        (m) =>
          typeof m.role === "string" &&
          typeof (m.content as Record<string, unknown>)?.sha === "string"
      ),
      "blob 模式 messages[i].content 必须是 {sha, bytes} 引用"
    );
    assert.ok(existsSync(join(convDir, "blobs")), "blobs/ 目录存在");

    // Read-side projection — using the same assertion values as full-mode-baseline.test.ts.
    const core = queryCoreFor(traceDir);
    const page = await queryPage(core, "baseline-conv", {});
    assert.deepEqual(
      page.records.map((r) => r.record_type),
      ["llm_call", "tool_call", "llm_call", "turn"]
    );

    const llmRows = (
      await queryPage(core, "baseline-conv", { record_type: "llm_call" })
    ).records;
    const llm1Row = llmRows.find((r) => r.llm_call_id === llm1)!;
    const llm2Row = llmRows.find((r) => r.llm_call_id === llm2)!;

    // Field-by-field against the full fixture's frozen values (same values as full-mode-baseline.test.ts).
    for (const [row, label, expected] of [
      [
        llm1Row,
        "llm-1",
        {
          messages_count: 2,
          tool_result_count: 0,
          input_tokens: 120,
          output_tokens: 30,
        },
      ],
      [
        llm2Row,
        "llm-2",
        {
          messages_count: 4,
          tool_result_count: 1,
          input_tokens: 260,
          output_tokens: 45,
        },
      ],
    ] as const) {
      for (const [key, value] of Object.entries(expected)) {
        assert.equal(
          row[key],
          value,
          `${label}.${key} must match full fixture`
        );
      }
    }
    assert.equal(
      llm1Row["first_message_preview"],
      '{"role":"system","content":"You are a helpful assistant."}'
    );
    assert.equal(
      llm1Row["last_message_preview"],
      '{"role":"user","content":[{"type":"text","text":"hello world"}]}'
    );
    assert.ok(!("last_assistant_preview" in llm1Row));
    assert.ok(!("tool_result_previews" in llm1Row));
    assert.equal(llm1Row["supplier_stop"], "success");
    assert.equal(llm1Row["status"], "ok");

    assert.equal(
      llm2Row["first_message_preview"],
      '{"role":"system","content":"You are a helpful assistant."}'
    );
    assert.equal(
      llm2Row["last_message_preview"],
      '{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu-1","content":"file-a\\nfile-b"}]}'
    );
    assert.equal(
      llm2Row["last_assistant_preview"],
      '{"role":"assistant","content":[{"type":"tool_use","id":"toolu-1","name":"bash","input":{"command":"ls"}}]}'
    );
    assert.deepEqual(llm2Row["tool_result_previews"], ["file-a\nfile-b"]);

    // tool_call projection (full fixture froze arguments/result verbatim).
    const toolPage = await queryPage(core, "baseline-conv", {
      record_type: "tool_call",
    });
    const toolRow = toolPage.records[0]!;
    assert.equal(toolRow["parent_llm_call_id"], llm1);
    assert.deepEqual(toolRow["arguments"], { command: "ls" });
    assert.equal(toolRow["result"], "file-a\nfile-b");
    assert.equal(toolRow["tool_name"], "bash");
    assert.ok(!("messages_count" in toolRow));

    // contains matches raw row substrings — in blob mode messages are sha references and the
    // body is not on the row, so contains filters nothing (0 hits is the true fact, forming the
    // dual-form contrast against the full fixture's 2 hits).
    const containsPage = await queryPage(core, "baseline-conv", {
      contains: "hello world",
    });
    assert.deepEqual(containsPage.records.length, 0);
  });
});
