/**
 * JsonlTraceService — JSONL file writer implementation.
 *
 * ADR-0003: ids are generated by the service (crypto.randomUUID);
 * camelToSnake lives only here and converts top-level schema keys only
 * (never recursing into messages / arguments / result content); appends are
 * synchronous (appendFileSync, no stream); no fsync (OS buffer); each
 * recordXxx try/catches, warns once on failure and returns undefined;
 * parentLlmCallId=undefined is written as JSON null (the key is never omitted).
 *
 * This file deliberately carries no self-healing layer (no auto-retry, no
 * checkpoint, no cost guardrail, no external observability export — the
 * reserved backend stub lives in observability-bridge).
 */

import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import { createHash, randomUUID } from "node:crypto";
import { dirname, join } from "node:path";
import { createOutputMask, currentSecretValues } from "../sandbox/index.js";
import { maybeRotate, type TraceRotationOptions } from "./rotation.js";
import type {
  TraceService,
  LlmCallRecord,
  ToolCallRecord,
  TurnRecord,
  SessionRecord,
  SandboxCmdRecord,
  VerificationRecord,
  GoalRecord,
  SubagentSpawnRecord,
  SubagentStopRecord,
  SubagentStateChangeRecord,
  SubagentStepRecord,
} from "./types.js";

export interface JsonlTraceOptions {
  /**
   * Trace directory (absolute or CWD-relative): writes go to
   * `<filePath>/<conversationId>.jsonl`, directory created lazily. Only the
   * subagent aggregate stream still uses directory mode; the main session
   * moved to file mode via `traceFilePath`, anchored at
   * `<baseDir>/projects/<slug>/<conversationId>/trace.jsonl` (ADR-0071).
   */
  filePath?: string;
  /**
   * Direct trace file path (main-session mode). The factory creates the
   * parent directory on first write; rotation only fires in directory mode (a
   * converged file path has no rotation targets). Mutually exclusive with
   * `filePath` — both set or both absent throws at factory construction.
   */
  traceFilePath?: string;
  /** Instance-bound conversation_id, stamped on every record (ADR-0003). */
  conversationId: string;
  /** Injectable writer (tests use an always-throw one). */
  writer?: (line: string) => void;
  /** Rotation caps; omitted values use the conservative defaults. */
  rotation?: TraceRotationOptions;
}

export interface TraceServiceWithHealth extends TraceService {
  readonly traceWriteFailures: number;
}

/** camelCase → snake_case (ADR-0003: centralized here). Top-level schema keys
 *  only, never inside content payloads. */
function camelToSnake(key: string): string {
  return key.replace(/[A-Z]/g, (m) => "_" + m.toLowerCase());
}

/** Convert a record's top-level keys to snake_case; values pass through as-is
 *  (including nested messages / arguments / result / error). */
function toSnakeCaseRecord<T extends object>(
  record: T
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    out[camelToSnake(key)] = value;
  }
  return out;
}

function sameSecretSet(
  left: ReadonlyArray<string>,
  right: ReadonlyArray<string>
): boolean {
  if (left.length !== right.length) return false;
  const rightSet = new Set(right);
  return left.every((value) => rightSet.has(value));
}

function isAlreadyPresentError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "EEXIST"
  );
}

/**
 * Shape tag for blob payloads (ADR-0036 amendment). Anthropic `content` has
 * two legal shapes — block array and plain string; the `{kind, v}` wrapper
 * lets the read side restore either losslessly (a string is never
 * mis-wrapped into an array, an array never mis-split).
 */
interface BlobPayload {
  kind: "str" | "blocks";
  v: unknown;
}

/**
 * Content-level blob references (ADR-0036 amendment): `messages[i]` stays a
 * `{role, content}` pair, with `content` replaced by `{sha, bytes}` — role
 * stays inline so the read-side `messageRole()` needs no change. Empty
 * content (empty string / empty array / null) is addressed the same way — it
 * has its own sha, no inline special case; body duplication is what dedup
 * actually saves (ADR-0071).
 */
function toBlobReferences(
  messages: ReadonlyArray<unknown>,
  traceDir: string,
  outputMask: ReturnType<typeof createOutputMask>
): Array<{ role: unknown; content: { sha: string; bytes: number } }> {
  const blobsDir = join(traceDir, "blobs");
  mkdirSync(blobsDir, { recursive: true });
  return messages.map((message) => {
    if (
      typeof message !== "object" ||
      message === null ||
      !("role" in message) ||
      !("content" in message)
    ) {
      throw new TypeError(
        "trace blob storage requires {role, content} message records"
      );
    }
    const { role, content } = message as {
      role: unknown;
      content: unknown;
    };
    const payload: BlobPayload = {
      kind: typeof content === "string" ? "str" : "blocks",
      v: content,
    };
    const serialized = JSON.stringify(payload) ?? "null";
    const masked = outputMask.mask(serialized);
    const bytes = Buffer.byteLength(masked, "utf8");
    const sha = createHash("sha256").update(masked, "utf8").digest("hex");
    try {
      writeFileSync(join(blobsDir, sha), masked, {
        encoding: "utf8",
        flag: "wx",
      });
    } catch (error) {
      if (!isAlreadyPresentError(error)) throw error;
    }
    return { role, content: { sha, bytes } };
  });
}

/**
 * SC20 follow-up: mask known secret values in the serialized JSONL line.
 *
 * This is intentionally coarse — we serialize the entire line, mask the
 * resulting string with the current secret values, and emit the masked
 * string. The mask is cached per factory instance and rebuilt only when the
 * current secret set changes.
 */
export function createJsonlTraceService(
  options: JsonlTraceOptions
): TraceServiceWithHealth {
  const { conversationId } = options;
  // Mode dispatch: filePath is a directory (subagent aggregate stream),
  // traceFilePath a file (main session anchored in the session folder).
  // Mutual exclusion is enforced fail-loud above so there is no silent
  // fallback to a cwd-relative `./trace/`.
  if (options.filePath === undefined && options.traceFilePath === undefined) {
    throw new Error(
      "JsonlTraceService requires either filePath (directory mode) or traceFilePath (file mode)"
    );
  }
  if (options.filePath !== undefined && options.traceFilePath !== undefined) {
    throw new Error(
      "JsonlTraceService received both filePath and traceFilePath — set exactly one"
    );
  }
  const filePath = options.filePath;
  const traceFilePath = options.traceFilePath;
  // Derivation: directory mode → targetFile = <dir>/<convId>.jsonl, targetDir
  // = <dir>; file mode → targetFile = traceFilePath, targetDir = its dirname.
  // The mutual-exclusion check above guarantees exactly one is set.
  const targetFile =
    traceFilePath !== undefined
      ? traceFilePath
      : join(filePath as string, `${conversationId}.jsonl`);
  const targetDir =
    filePath !== undefined ? filePath : dirname(traceFilePath as string);
  // Rotation (the old `<dir>/<convId>.1.jsonl` chain) stays directory-mode only; file mode has no targets.
  if (filePath !== undefined) {
    maybeRotate(filePath, options.rotation);
  }
  let secretValues = currentSecretValues();
  let outputMask = createOutputMask(secretValues);
  function currentOutputMask(): ReturnType<typeof createOutputMask> {
    const currentValues = currentSecretValues();
    if (!sameSecretSet(secretValues, currentValues)) {
      secretValues = currentValues;
      outputMask = createOutputMask(secretValues);
    }
    return outputMask;
  }
  // mkdir deferred to first write: construction does no IO. Failures (e.g. a
  // same-named file occupying the path) are caught by the recordXxx warn-once
  // path (ADR-0003), never thrown at construction to kill a live turn. Only
  // the default writer creates directories — with an injected writer the
  // caller owns persistence, so no IO side effect is forced here.
  let dirReady = false;
  const writer: (line: string) => void =
    options.writer ??
    ((line: string): void => {
      if (!dirReady) {
        mkdirSync(targetDir, { recursive: true });
        dirReady = true;
      }
      appendFileSync(targetFile, line + "\n", "utf8");
    });

  // Instance-level hygiene: warn once on the first write failure, then stay quiet (ADR-0003).
  let warnedOnce = false;
  let traceWriteFailures = 0;

  function recordFailure(err: unknown): void {
    traceWriteFailures += 1;
    if (!warnedOnce) {
      warnedOnce = true;
      console.warn("[JsonlTraceService] write failed:", err);
    }
  }

  function writeLine(payload: Record<string, unknown>): void {
    writer(currentOutputMask().mask(JSON.stringify(payload)));
  }

  const service: TraceServiceWithHealth = {
    get traceWriteFailures() {
      return traceWriteFailures;
    },
    async recordLlmCall(record: LlmCallRecord): Promise<string | undefined> {
      const id = randomUUID();
      const fullLine: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "llm_call",
        llm_call_id: id,
        ...toSnakeCaseRecord(record),
      };
      // No inline fallback: blobs are the only storage mode. If blob IO
      // fails, nothing is written for this call (warn-once, return undefined,
      // never throw) — the turn survives.
      if (record.messages !== undefined) {
        try {
          fullLine.messages = toBlobReferences(
            record.messages,
            targetDir,
            currentOutputMask()
          );
        } catch (err) {
          recordFailure(err);
          return undefined;
        }
      }
      try {
        writeLine(fullLine);
        return id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordToolCall(record: ToolCallRecord): Promise<string | undefined> {
      const id = randomUUID();
      const snake = toSnakeCaseRecord(record);
      // undefined parent must land as literal null, not an omitted key
      // (JSON.stringify drops undefined values), hence the explicit ?? null.
      snake.parent_llm_call_id = record.parentLlmCallId ?? null;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "tool_call",
        tool_call_id: id,
        ...snake,
      };
      try {
        writeLine(line);
        return id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordTurn(record: TurnRecord): Promise<string | undefined> {
      // Caller-pregenerated id wins (subagent instrumentation needs the turn
      // id before the turn ends); fall back to generating one. The `id` key is
      // removed from the snake copy — `turn_id` is the single carrier.
      const id = record.id ?? randomUUID();
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "turn",
        turn_id: id,
        ...snake,
      };
      try {
        writeLine(line);
        return id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordSession(record: SessionRecord): Promise<string | undefined> {
      const id = randomUUID();
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "session",
        session_id: id,
        ...toSnakeCaseRecord(record),
      };
      try {
        writeLine(line);
        return id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordSandboxCmd(
      record: SandboxCmdRecord
    ): Promise<string | undefined> {
      const id = randomUUID();
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "sandbox_cmd",
        sandbox_cmd_id: id,
        ...toSnakeCaseRecord(record),
      };
      try {
        writeLine(line);
        return id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordVerification(
      record: VerificationRecord
    ): Promise<string | undefined> {
      // id comes from the caller here (no randomUUID). Top-level
      // verification_id carries it; other top-level keys go through
      // toSnakeCaseRecord, with the original id key dropped to avoid doubles.
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "verification",
        verification_id: record.id,
        ...snake,
      };
      try {
        writeLine(line);
        return record.id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordGoal(record: GoalRecord): Promise<string | undefined> {
      // Same shape as recordVerification: caller-supplied id, carried by
      // top-level goal_id; original id key dropped from the snake copy.
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      // GoalRecord carries a redundant conversationId field, but
      // conversation_id is bound to the factory instance — drop it from the
      // snake copy so the binding always wins.
      delete snake.conversation_id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "goal",
        goal_id: record.id,
        ...snake,
      };
      try {
        writeLine(line);
        return record.id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    // ─── Subagent lifecycle events ───────────────────────────────────────
    // Same shape as recordVerification / recordGoal: caller supplies the id
    // (= manager taskId), no randomUUID. Top-level subagent_id carries it;
    // optional fields are present only when the caller has a real source.
    // Failures return undefined, never throw.

    async recordSubagentSpawn(
      record: SubagentSpawnRecord
    ): Promise<string | undefined> {
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "subagent_spawn",
        subagent_id: record.id,
        ...snake,
      };
      try {
        writeLine(line);
        return record.id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordSubagentStop(
      record: SubagentStopRecord
    ): Promise<string | undefined> {
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "subagent_stop",
        subagent_id: record.id,
        ...snake,
      };
      try {
        writeLine(line);
        return record.id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordSubagentStateChange(
      record: SubagentStateChangeRecord
    ): Promise<string | undefined> {
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "subagent_state_change",
        subagent_id: record.id,
        ...snake,
      };
      try {
        writeLine(line);
        return record.id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },

    async recordSubagentStep(
      record: SubagentStepRecord
    ): Promise<string | undefined> {
      // Only shape difference: the id carrier is subagent_step_id — a step id
      // is unique per step, unlike the other three records where id === taskId.
      const snake = toSnakeCaseRecord(record);
      delete snake.id;
      const line: Record<string, unknown> = {
        conversation_id: conversationId,
        record_type: "subagent_step",
        subagent_step_id: record.id,
        ...snake,
      };
      try {
        writeLine(line);
        return record.id;
      } catch (err) {
        recordFailure(err);
        return undefined;
      }
    },
  };
  return service;
}
