export type { SessionStoreError, SessionStoreErrorKind } from "./errors.js";
export type {
  CheckpointRecord,
  GoalHistoryEntry,
  GoalSource,
  GoalState,
  GoalStatus,
  InterruptReason,
  SessionFileV1,
} from "./schema.js";
export { MAX_WORKSPACE_ROOT_CHARS } from "../../config/workspace-root.js";
export {
  CURRENT_SCHEMA_VERSION,
  extractGoal,
  extractTitle,
  isNewFormatSession,
  isSessionFileV1,
  MAX_GOAL_CHARS,
  NATIVE_STATE_FORMAT_VERSION,
  pinGoal,
  sanitizeSessionFile,
  validateGoalText,
  validateSessionFile,
} from "./schema.js";
export {
  appendCheckpoint,
  decideCheckpointPersist,
  resolveRewindAnchor,
  shouldPersistCheckpoint,
  splitTurns,
  toInterruptReason,
  turnSliceEnd,
  withCheckpointAnchors,
  type CheckpointPersistDecision,
  type TurnSlice,
} from "./checkpoint.js";
export { closeoutOrphanToolUses } from "./closeout-projection.js";
export {
  chainFromHead,
  factPayloadField,
  headChainEvents,
  isNativeStateBoundary,
  isStopReason,
  jsonDeepEqual,
  latestTitleText,
  messageEventId,
  parseSessionJsonl,
  projectSessionLog,
  resolvePublishedNativeState,
  resolveTurnOutcomes,
  serializeSessionLog,
  SESSION_JSONL_EXT,
  sessionFileToJsonl,
  type FileIntentPosition,
  type FileIntentTarget,
  type ParsedSessionLog,
  type PublishedNativeStateSelection,
  type SessionEventRecord,
  type SessionFileIntentRecord,
  type SessionHeadRecord,
  type SessionHeaderRecord,
  type SessionJsonlError,
  type SessionJsonlRecord,
  type SessionNativeStateRecord,
  type SessionOperationFactRecord,
  type SessionOutcomeRecord,
  type SecurityInterruptionRecord,
  type SecurityInterruptionItem,
  type SecurityInterruptionCleanup,
  type SessionTailRecord,
  type SessionTitleRecord,
} from "./jsonl.js";
export {
  forbiddenPersistedField,
  isNativeStateSha,
  nativeStateBlobsDir,
  nativeStateBodySha,
  operationFactInputField,
  parseNativeStateBody,
  readNativeStateBody,
  validateNativeStateSnapshot,
  writeNativeStateBody,
  NATIVE_STATE_BLOBS_DIR_NAME,
  type NativeStateBodyError,
} from "./native-state-store.js";
export { createNativeStatePort } from "./native-state-port-host.js";
export {
  createRuntimePersistenceBinder,
  type RuntimePersistenceHostDeps,
} from "./runtime-persistence-host.js";
export {
  buildRewindTargetsFromLog,
  type LedgerRewindTarget,
} from "./rewind-targets.js";
export {
  applyCodeRestore,
  buildCodeRestorePlan,
  type ApplyCodeRestoreOpts,
  type CodeRestoreError,
  type CodeRestoreOp,
  type CodeRestorePlan,
  type CodeRestoreReport,
  type CodeRestoreSkip,
  type CodeRestoreTranscript,
} from "./code-preimage.js";
export {
  appendWorkerTranscript,
  isWorkerTranscriptPathSafe,
  loadWorkerPreimageEvents,
  loadWorkerTranscript,
  readWorkerSpawnToolUseId,
  type WorkerTranscriptLocation,
} from "./worker-transcript.js";
export { readWorkerInFlightToolName } from "./worker-activity.js";
export {
  resolveConversationDir,
  resolveConversationTraceFilePath,
  resolveProjectSessionDir,
  resolveSubagentTraceDir,
  SessionStore,
  SUBAGENT_TRACE_DIR_NAME,
  TRACE_FILE_NAME,
  type AppendOperationFactInput,
  type SessionListEntry,
  type SessionBindingStatus,
} from "./session-store.js";
export {
  RECOVERY_IN_PROGRESS_LABEL,
  reconcileFileIntents,
  recoverSession,
  type FileHandlingReason,
  type FileTargetVerdict,
  type RecoveredFileOperation,
  type RecoveryBlockedReason,
  type RecoveryHandlingItem,
  type RecoveryInProgressLabel,
  type RecoveryStatus,
  type ReconcileInput,
  type ReconcileResult,
  type RecoverSessionOptions,
  type RestoredTurnOutcome,
  type SessionRecoveryReport,
  type ToolOperationSettlement,
} from "./recovery.js";
