/**
 * SC13 — session tmp, across a real reopen in a SECOND real process.
 * `specs/session-checkpoint-architecture.md:165` — "reopening reads the current
 * real session-tmp files without creating tmp checkpoints. Missing/incomplete
 * dispensable tmp content does not masquerade as saved progress and can be
 * regenerated by explicit subsequent execution."
 *
 * The repo's own definition of the content this clause is about (spec:112,
 * `tests/session-api/store/recovery.test.ts:557`): the session-scoped host
 * directory ADR-0074 put inside the session folder and ADR-0092 kept at its
 * host path — `mainSessionFenceTmpPath`, i.e. `<sessionFolder>/fence-tmp`.
 * Its intermediates are the dispensable part. This file drives that exact
 * directory through the production `resolveSessionFenceTmp` the write tools
 * resolve, not a stand-in tmp dir.
 *
 * The tmp content here is written by the production `write_file` with that pad
 * resolved, and read back by the production `read_file` with the same pad. The
 * preimage capture is deliberately NOT wired for these writes: the pad is
 * session scratch, not workspace code (spec:112 "no extra snapshots"), and the
 * code-evidence contract (SC9 / SC9a) is covered by
 * `tests/session-api/store/capture-disabled-needs-handling.test.ts`. What these
 * cases assert is the tmp content's own lifecycle.
 *
 * Every reopen runs in a real second process over the same real temp pool, via
 * the reused harness `tests/session-api/crash/crash-harness.ts`, unmodified.
 */
import assert from "node:assert/strict";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, describe, it } from "vitest";

import { createReadFileTool } from "../../../src/harness/aci/tools/read-file.ts";
import { createWriteFileTool } from "../../../src/harness/aci/tools/write-file.ts";
import { mainSessionFenceTmpPath } from "../../../src/harness/sandbox/fence-tmp.ts";
import {
  parseSessionJsonl,
  type ParsedSessionLog,
} from "../../../src/session-api/store/jsonl.ts";
import type { RecoveredFileOperation } from "../../../src/session-api/store/recovery-reconcile.ts";
import type { RecoveryStatus } from "../../../src/session-api/store/recovery-status.ts";
import type { RestoredTurnOutcome } from "../../../src/session-api/store/recovery.ts";
import type { NativeStateMessage } from "../../../src/shared/native-state-port.ts";
import {
  createCrashHost,
  disposeAllCrashHosts,
  realConversationDir,
  realLogBytes,
  realSessionFingerprint,
  runHostToCompletion,
  runRoleInFreshProcess,
  type CrashHost,
} from "../crash/crash-harness.ts";

const CRASH_TEST_TIMEOUT = 180_000;

const SCRATCH = "intermediate-a";
const INTERMEDIATE = "half-finished build output\n";
const REGENERATED = "regenerated by the next explicit execution\n";

interface ReopenResult {
  readonly status: RecoveryStatus;
  readonly savedMessageCount: number;
  readonly restoredContext: ReadonlyArray<NativeStateMessage> | null;
  readonly messages: ReadonlyArray<NativeStateMessage>;
  readonly outcome: RestoredTurnOutcome | null;
  readonly operations: ReadonlyArray<RecoveredFileOperation>;
  readonly tripwire: {
    readonly armed: boolean;
    readonly hits: ReadonlyArray<{ code: string; op_index: number }>;
  };
}

/** The production session tmp for this session, resolved the way the tools
 *  resolve it. */
const sessionTmpDir = (host: CrashHost): string =>
  mainSessionFenceTmpPath(realConversationDir(host));

/** Every tmp file's exact bytes, so "unchanged" is observable, not assumed. */
async function tmpTree(
  dir: string
): Promise<ReadonlyArray<{ readonly rel: string; readonly bytes: string }>> {
  try {
    const names = (await readdir(dir, { recursive: true })).sort();
    const out: { rel: string; bytes: string }[] = [];
    for (const name of names) {
      out.push({
        rel: name,
        bytes: await readFile(join(dir, name), "utf8"),
      });
    }
    return out;
  } catch (err) {
    if ((err as { code?: string }).code === "ENOENT") return [];
    throw err;
  }
}

/** One real tool execution that writes into the session tmp. The pad is
 *  resolved by the production `resolveSessionFenceTmp` from the session
 *  project dir and the conversation id, exactly as a host's write tool does. */
async function writeSessionTmp(
  host: CrashHost,
  name: string,
  content: string
): Promise<void> {
  const tool = createWriteFileTool(host.workspaceRoot, {
    projectDir: host.projectDir,
  });
  const out = (await tool.handler(
    { path: join(sessionTmpDir(host), name), content },
    { conversationId: host.conversationId }
  )) as { readonly output: string };
  assert.ok(
    out.output.includes("[write_file] wrote"),
    `the write of ${name} into session tmp must run, got: ${out.output}`
  );
}

async function readSessionTmp(host: CrashHost, name: string): Promise<string> {
  const tool = createReadFileTool(host.workspaceRoot, {
    projectDir: host.projectDir,
  });
  return (await tool.handler(
    { path: join(sessionTmpDir(host), name) },
    { conversationId: host.conversationId }
  )) as string;
}

/** A real host process writes the log, then a real second process reopens it. */
async function seedSession(conversationId: string): Promise<CrashHost> {
  const host = await createCrashHost({ prefix: "iknow-sc13-", conversationId });
  await runHostToCompletion({
    host,
    request: {
      role: "publish",
      plan: [
        { op: "create", cwd: host.workspaceRoot },
        {
          op: "appendEvents",
          messages: [
            { role: "user", content: [{ type: "text", text: "stage it" }] },
            {
              role: "assistant",
              content: [{ type: "text", text: "staging" }],
            },
          ],
        },
        {
          op: "appendNativeState",
          anchorEventId: "e0",
          boundary: "input",
          messages: [
            { role: "user", content: [{ type: "text", text: "stage it" }] },
          ],
        },
      ],
    },
    timeoutMs: CRASH_TEST_TIMEOUT,
  });
  return host;
}

const reopen = (host: CrashHost): Promise<ReopenResult> =>
  runRoleInFreshProcess<ReopenResult>({
    host,
    request: { role: "reopen_chat" },
    timeoutMs: CRASH_TEST_TIMEOUT,
  });

const logRecords = async (host: CrashHost): Promise<ParsedSessionLog> =>
  parseSessionJsonl(await realLogBytes(host));

afterEach(async () => {
  await disposeAllCrashHosts();
});

describe("SC13 session tmp across a real reopen", () => {
  it(
    "SC13 (a): reopening reads the current session-tmp files and creates no tmp checkpoint",
    async () => {
      const host = await seedSession("sc13-intact-tmp");
      await mkdir(sessionTmpDir(host), { recursive: true });
      await writeFile(join(sessionTmpDir(host), SCRATCH), INTERMEDIATE, "utf8");
      const tmpBefore = await tmpTree(sessionTmpDir(host));
      const recordsBefore = await logRecords(host);
      const fingerprintBefore = await realSessionFingerprint(host);
      assert.equal(tmpBefore.length, 1, "the fixture has real tmp content");

      const reopened = await reopen(host);

      assert.equal(reopened.status.status, "recovered");
      assert.deepEqual(
        await tmpTree(sessionTmpDir(host)),
        tmpBefore,
        "the reopen neither checkpointed nor copied the session tmp"
      );
      assert.deepEqual(
        (await logRecords(host)).records,
        recordsBefore.records,
        "no record was appended for tmp content"
      );
      assert.equal(
        await realSessionFingerprint(host),
        fingerprintBefore,
        "the whole session folder, tmp included, is byte-identical"
      );
      // The reread is of the CURRENT file: a later read returns what is on
      // disk now, not a restored image.
      await writeFile(
        join(sessionTmpDir(host), SCRATCH),
        "edited after the reopen\n",
        "utf8"
      );
      assert.ok(
        (await readSessionTmp(host, SCRATCH)).includes(
          "edited after the reopen"
        ),
        "what a later turn reads is the current tmp file"
      );
    },
    CRASH_TEST_TIMEOUT
  );

  it(
    "SC13 (b): missing or incomplete tmp content is not saved progress and not an operator problem",
    async () => {
      const host = await seedSession("sc13-damaged-tmp");
      const tmpDir = sessionTmpDir(host);
      await mkdir(tmpDir, { recursive: true });
      await writeFile(join(tmpDir, SCRATCH), INTERMEDIATE, "utf8");
      const intact = await reopen(host);
      assert.equal(intact.status.status, "recovered");

      // Missing: the dispensable part is gone.
      await rm(join(tmpDir, SCRATCH));
      const recordsBefore = await logRecords(host);
      const afterMissing = await reopen(host);
      assert.equal(
        afterMissing.status.status,
        "recovered",
        "absent dispensable content is neither a failure nor a handling item"
      );
      assert.equal(
        afterMissing.savedMessageCount,
        intact.savedMessageCount,
        "progress is the published state alone, tmp content or not"
      );
      assert.deepEqual(afterMissing.status, intact.status);
      assert.deepEqual(
        await tmpTree(tmpDir),
        [],
        "the reopen did not regenerate the absent tmp content"
      );
      assert.deepEqual(
        (await logRecords(host)).records,
        recordsBefore.records,
        "no tmp checkpoint was written while the content was absent"
      );

      // Incomplete: the dispensable part is present but truncated.
      await writeFile(join(tmpDir, SCRATCH), "half-f", "utf8");
      const afterPartial = await reopen(host);
      assert.equal(afterPartial.status.status, "recovered");
      assert.equal(
        afterPartial.savedMessageCount,
        intact.savedMessageCount,
        "a partial intermediate is not counted as progress either"
      );
      assert.deepEqual(afterPartial.status, intact.status);
      assert.deepEqual(afterPartial.operations, intact.operations);
      assert.equal(
        await readFile(join(tmpDir, SCRATCH), "utf8"),
        "half-f",
        "the reopen neither completed nor rewrote the partial file"
      );
    },
    CRASH_TEST_TIMEOUT
  );

  it(
    "SC13 (c): an explicit subsequent execution regenerates the dispensable content, and only then does it exist",
    async () => {
      const host = await seedSession("sc13-regenerated-tmp");
      const tmpDir = sessionTmpDir(host);
      await mkdir(tmpDir, { recursive: true });
      await writeFile(join(tmpDir, SCRATCH), INTERMEDIATE, "utf8");
      await rm(join(tmpDir, SCRATCH));
      const afterMissing = await reopen(host);
      assert.equal(afterMissing.status.status, "recovered");
      assert.deepEqual(
        await tmpTree(tmpDir),
        [],
        "absent before the execution"
      );

      const recordsBefore = await logRecords(host);
      await writeSessionTmp(host, SCRATCH, REGENERATED);

      assert.equal(
        await readFile(join(tmpDir, SCRATCH), "utf8"),
        REGENERATED,
        "the explicit execution regenerated the dispensable content"
      );
      assert.ok(
        (await readSessionTmp(host, SCRATCH)).includes("regenerated"),
        "the regenerated content is the current file a later turn reads"
      );
      assert.deepEqual(
        (await logRecords(host)).records,
        recordsBefore.records,
        "regenerating tmp content checkpoints nothing"
      );

      // Progress exists as before: the tmp file is a fact of the execution,
      // not saved session progress.
      const afterRegenerated = await reopen(host);
      assert.equal(afterRegenerated.status.status, "recovered");
      assert.equal(
        afterRegenerated.savedMessageCount,
        afterMissing.savedMessageCount,
        "regenerated tmp content adds no saved progress"
      );
      assert.deepEqual(afterRegenerated.status, afterMissing.status);
    },
    CRASH_TEST_TIMEOUT
  );
});
