/**
 * tests/harness/permission/stage2-floor-differential.test.ts
 *
 * The Stage 2 floor, as a thing that can fail: "the migration newly denies
 * nothing, and newly allows no real operand access."
 *
 * `tests/fixtures/shell-divergence/stage2-differential.jsonl` is generated by
 * `scripts/stage2-floor-differential-generate.ts`, which dual-runs every command
 * shape through the PRE-migration oracle (the base commit's own `hard-walls.ts`,
 * materialized by `git show`) and through the tree, then labels each row with
 * the closed divergence vocabulary. This file re-reads that fixture against
 * LIVE HEAD behaviour, so it grades the claim rather than the day it was
 * measured:
 *
 *   (a) no row went from allowed to denied;
 *   (b) every row the pre-state denied and HEAD now allows carries one of the
 *       licensed relaxation classes — an unlabeled or newly-appearing allow
 *       fails here, and a row the generator could not license arrives already
 *       labeled `open`, which fails too;
 *   (c) every row's recorded HEAD hit still matches what HEAD computes now,
 *       which is what catches a future `id`/`pattern` move sneaking in;
 *   (d) the authorized `{id, pattern}` move is exactly the one the fork-bomb
 *       shape owns, and no other row moved;
 *   (e) every relaxation row cites the SC-GATES-3 clause its own class names,
 *       and the generator's carrier list still matches the wall's by membership.
 *
 * Nothing here re-derives a label from product code: the labels are read from
 * the committed fixture, so a change to the rules cannot also rewrite its own
 * excuse. Corpus input is inert text — this file parses and compares, it never
 * executes a command.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  commandContainsSensitivePath,
  findDangerousPattern,
  type DangerousPatternHit,
} from "../../../src/harness/permission/hard-walls.js";
import {
  EXECUTION_CARRIER_NAMES,
  STORED_OR_RUNNED_OPERAND_NAMES,
  TRANSPARENT_WRAPPERS,
  carrierFloorShapes,
} from "../../../scripts/stage2-floor-differential-generate.ts";

type WallName = "pattern" | "sensitive";

type DivergenceLabel =
  "same" | "expected-relaxation" | "authorized-id-move" | "fixed" | "open";

/** The licensed relaxation classes: quote/heredoc, inert-span, operand-scope. */
type RelaxationClass = "1" | "2" | "3";

type WallValue = DangerousPatternHit | boolean | null;

interface FixtureRow {
  readonly command: string;
  readonly wall: WallName;
  readonly base: WallValue;
  readonly head: WallValue;
  readonly label: DivergenceLabel;
  readonly class?: RelaxationClass;
  readonly clause?: string;
}

const repoRoot = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  ".."
);
const corpusDir = join(repoRoot, "tests", "fixtures", "shell-corpus");
const fixturePath = join(
  repoRoot,
  "tests",
  "fixtures",
  "shell-divergence",
  "stage2-differential.jsonl"
);

/** The admitted label set, closed: a label outside it is a shape violation. */
const ADMITTED_LABELS: readonly DivergenceLabel[] = [
  "same",
  "expected-relaxation",
  "authorized-id-move",
  "fixed",
  "open",
];

/** Which relaxation classes each wall may be excused under. */
const LICENSED_CLASSES: Record<WallName, readonly RelaxationClass[]> = {
  pattern: ["1", "3"],
  sensitive: ["2"],
};

/**
 * SC-GATES-3: a tagged relaxation must be tagged to a clause. The citation names
 * the spec, the gate and the class it belongs to — one class number per row, and
 * it must be the row's own.
 */
const CLAUSE_CITATION: Record<RelaxationClass, RegExp> = {
  "1": /^specs\/hard-wall-ast-migration\.md SC-GATES-3 class \(1\) quote\/heredoc\b/,
  "2": /^specs\/hard-wall-ast-migration\.md SC-GATES-3 class \(2\) inert-span\b/,
  "3": /^specs\/hard-wall-ast-migration\.md SC-GATES-3 class \(3\) operand-scope\b/,
};

/**
 * The one authorized `{base, head}` id move. A denial whose tier never changed
 * but whose reported id did, owned by the structural fork-bomb rule.
 */
const AUTHORIZED_MOVE = {
  base: { id: "bare-metachar", pattern: "|" },
  head: { id: "destructive-disk", pattern: ":(){ :|:& };:" },
} as const;

// --------------------------------------------------------------------------
// fixture loading — a violating line fails the load, nothing is skipped
// --------------------------------------------------------------------------

function describeRow(row: { command: string; wall: string }): string {
  return `${row.wall} ${JSON.stringify(row.command).slice(0, 70)}`;
}

function readHit(value: unknown, field: string): DangerousPatternHit {
  const hit = value as Partial<DangerousPatternHit> | null;
  if (
    typeof hit !== "object" ||
    hit === null ||
    typeof hit.id !== "string" ||
    typeof hit.pattern !== "string"
  ) {
    throw new Error(`\`${field}\` is not an {id, pattern} object`);
  }
  return { id: hit.id as DangerousPatternHit["id"], pattern: hit.pattern };
}

function readWallValue(
  value: unknown,
  wall: WallName,
  field: string
): WallValue {
  if (wall === "sensitive") {
    if (typeof value !== "boolean")
      throw new Error(`\`${field}\` is not a boolean`);
    return value;
  }
  if (value === null) return null;
  return readHit(value, field);
}

function parseRow(line: string, index: number): FixtureRow {
  const where = `line ${index + 1}`;
  const raw = JSON.parse(line) as Record<string, unknown>;
  const wall = raw.wall;
  if (wall !== "pattern" && wall !== "sensitive")
    throw new Error(`${where}: wall is ${JSON.stringify(wall)}`);
  if (typeof raw.command !== "string" || raw.command.length === 0)
    throw new Error(`${where}: command is missing or empty`);
  const label = raw.label as DivergenceLabel;
  if (!ADMITTED_LABELS.includes(label))
    throw new Error(
      `${where}: label ${JSON.stringify(raw.label)} is not admitted`
    );
  const cls = raw.class;
  if (cls !== undefined && !["1", "2", "3"].includes(cls as string))
    throw new Error(`${where}: class ${JSON.stringify(cls)} is unknown`);
  const clause = raw.clause;
  if (clause !== undefined && typeof clause !== "string")
    throw new Error(`${where}: clause is ${JSON.stringify(clause)}`);
  const row: FixtureRow = {
    command: raw.command,
    wall,
    base: readWallValue(raw.base, wall, "base"),
    head: readWallValue(raw.head, wall, "head"),
    label,
    ...(cls === undefined ? {} : { class: cls as RelaxationClass }),
    ...(clause === undefined ? {} : { clause: clause as string }),
  };
  assertLabelIsCoherent(row, where);
  return row;
}

function sameValue(left: WallValue, right: WallValue): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

/** The recorded three fields must tell one consistent story about the fixture. */
function assertLabelIsCoherent(row: FixtureRow, where: string): void {
  if (row.label === "same") {
    if (!sameValue(row.base, row.head))
      throw new Error(`${where}: labeled same but the two sides differ`);
    if (row.class !== undefined)
      throw new Error(`${where}: a same row carries no relaxation class`);
    if (row.clause !== undefined)
      throw new Error(`${where}: a same row carries no citation`);
    return;
  }
  if (row.label === "expected-relaxation") {
    if (denies(row.head) || !denies(row.base))
      throw new Error(
        `${where}: labeled relaxation but did not go deny -> allow`
      );
    if (row.class === undefined)
      throw new Error(`${where}: a relaxation row must name its class`);
    return;
  }
  if (row.clause !== undefined)
    throw new Error(`${where}: only a relaxation row carries a citation`);
  if (row.label === "authorized-id-move") {
    const authorized =
      sameValue(row.base, AUTHORIZED_MOVE.base) &&
      sameValue(row.head, AUTHORIZED_MOVE.head);
    if (!authorized || !denies(row.head))
      throw new Error(
        `${where}: labeled id move but is not the authorized pair`
      );
  }
}

/** The citation a relaxation row must carry: its own class, from its own spec. */
function citesItsOwnClass(row: FixtureRow): boolean {
  const clause = row.clause;
  if (typeof clause !== "string" || clause.length === 0) return false;
  return CLAUSE_CITATION[row.class as RelaxationClass].test(clause);
}

function loadFixture(): FixtureRow[] {
  const lines = readFileSync(fixturePath, "utf8").split("\n");
  return lines
    .filter((line) => line.length > 0)
    .map((line, index) => parseRow(line, index));
}

function loadCorpusCommands(file: string): string[] {
  return readFileSync(join(corpusDir, file), "utf8")
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => (JSON.parse(line) as { command: string }).command);
}

const rows = loadFixture();
const patternRows = rows.filter((row) => row.wall === "pattern");
const sensitiveRows = rows.filter((row) => row.wall === "sensitive");

/** What HEAD answers for one wall right now, in the fixture's own encoding. */
function liveHead(row: FixtureRow): WallValue {
  return row.wall === "pattern"
    ? findDangerousPattern(row.command)
    : commandContainsSensitivePath(row.command);
}

function denies(value: WallValue): boolean {
  return typeof value === "boolean" ? value : value !== null;
}

// ==========================================================================

describe("stage 2 floor differential: the fixture is a graded artifact", () => {
  it("holds rows for both walls and is not empty", () => {
    expect(rows.length, "no differential rows were generated").toBeGreaterThan(
      0
    );
    expect(patternRows.length).toBeGreaterThan(0);
    expect(sensitiveRows.length).toBeGreaterThan(0);
    expect(
      new Set(rows.map((row) => row.command)).size,
      "every command is measured on both walls exactly once"
    ).toBe(rows.length / 2);
  });

  it("covers every command the committed shape fixtures hold", () => {
    const covered = new Set(rows.map((row) => row.command));
    for (const file of ["benign.jsonl", "substitution.jsonl"]) {
      for (const command of loadCorpusCommands(file)) {
        expect(
          covered.has(command),
          `${file} command is absent from the differential: ${JSON.stringify(command)}`
        ).toBe(true);
      }
    }
  });
});

describe("(a) the migration newly denies nothing", () => {
  it("no row went from allowed on the pre-state to denied on live HEAD", () => {
    const newlyDenied = rows
      .filter((row) => !denies(row.base) && denies(liveHead(row)))
      .map(describeRow);
    expect(newlyDenied, "new denies appeared over the pre-state").toEqual([]);
  });

  it("no row was recorded as an unlicensed divergence", () => {
    const open = rows.filter((row) => row.label === "open").map(describeRow);
    expect(open, "an open divergence blocks the merge").toEqual([]);
  });
});

describe("(b) every new allow is a licensed relaxation", () => {
  it("each allow over a pre-state deny carries that wall's licensed class", () => {
    const violations: string[] = [];
    for (const row of rows) {
      if (!denies(row.base) || denies(liveHead(row))) continue;
      const licensed = LICENSED_CLASSES[row.wall];
      if (row.label !== "expected-relaxation") {
        violations.push(
          `${describeRow(row)} -> ${row.label}, expected expected-relaxation`
        );
      } else if (!licensed.includes(row.class as RelaxationClass)) {
        violations.push(
          `${describeRow(row)} -> class ${JSON.stringify(row.class)}, expected one of ${licensed.join("/")}`
        );
      }
    }
    expect(violations, "unlicensed relaxations").toEqual([]);
  });

  it("each licensed class has a supplier, so the class is not an empty excuse", () => {
    for (const [wall, classes] of Object.entries(LICENSED_CLASSES)) {
      for (const cls of classes) {
        const suppliers = rows.filter(
          (row) => row.wall === wall && row.class === cls
        );
        expect(
          suppliers.length,
          `class ${cls} has no row on the ${wall} wall`
        ).toBeGreaterThan(0);
      }
    }
  });
});

describe("(c) live HEAD still answers what the fixture recorded", () => {
  it("every row's recorded hit matches HEAD now, id and pattern alike", () => {
    const drift = rows
      .filter(
        (row) => JSON.stringify(liveHead(row)) !== JSON.stringify(row.head)
      )
      .map((row) => {
        const from = JSON.stringify(row.head);
        const to = JSON.stringify(liveHead(row));
        return `${describeRow(row)}: recorded ${from}, HEAD now ${to}`;
      });
    expect(
      drift,
      "HEAD moved under the fixture; re-run the generator and review the diff"
    ).toEqual([]);
  });
});

describe("(d) exactly the one authorized id move", () => {
  it("the moved set is the fork-bomb pair and nothing else moved", () => {
    const moved = patternRows.filter(
      (row) =>
        denies(row.base) &&
        denies(row.head) &&
        JSON.stringify(row.base) !== JSON.stringify(row.head)
    );
    const labeled = rows.filter((row) => row.label === "authorized-id-move");
    expect(
      moved.map(describeRow),
      "more rows moved their {id, pattern} than the one authorized pair"
    ).toHaveLength(1);
    expect(labeled.map(describeRow)).toEqual(moved.map(describeRow));
    for (const row of moved) {
      expect(row.command).toBe(AUTHORIZED_MOVE.head.pattern);
      expect(row.base).toEqual(AUTHORIZED_MOVE.base);
      expect(row.head).toEqual(AUTHORIZED_MOVE.head);
    }
  });

  it("the move keeps the tier: denied before, denied now", () => {
    for (const row of rows.filter(
      (each) => each.label === "authorized-id-move"
    )) {
      expect(denies(row.base), "the pre-state must deny the shape").toBe(true);
      expect(denies(liveHead(row)), "HEAD must still deny the shape").toBe(
        true
      );
    }
  });
});

describe("(e) every excuse names its clause", () => {
  it("each relaxation row cites the clause its own class names", () => {
    const relaxations = rows.filter(
      (row) => row.label === "expected-relaxation"
    );
    expect(
      relaxations.length,
      "the fixture licenses nothing, so the citation gate is vacuous"
    ).toBeGreaterThan(0);
    const uncited = relaxations
      .filter((row) => !citesItsOwnClass(row))
      .map((row) => `${describeRow(row)} cites ${JSON.stringify(row.clause)}`);
    expect(uncited, "a relaxation without its own clause cited").toEqual([]);
  });
});

describe("(e) the carrier roster is one list, not two opinions", () => {
  /**
   * The wall's set is module-private on purpose: its witness must not import
   * the rules it grades. Membership is therefore compared by reading the two
   * declarations, so a name added or dropped on either side fails here instead
   * of quietly re-tagging a carrier row `same`.
   */
  function declaredNames(source: string, constant: string): string[] {
    const at = source.indexOf(`const ${constant}`);
    if (at < 0)
      throw new Error(
        `${constant} is no longer declared in the source — the two lists can ` +
          "no longer be compared, so re-point this test rather than deleting it"
      );
    const block = source.slice(at, source.indexOf("])", at));
    return [...block.matchAll(/"([a-z0-9]+)"/g)]
      .map((entry) => entry[1] as string)
      .sort();
  }

  const wallSource = readFileSync(
    join(repoRoot, "src", "harness", "permission", "hard-walls.ts"),
    "utf8"
  );

  it("the ledger's carrier list and the wall's agree by membership", () => {
    expect(declaredNames(wallSource, "EXECUTION_CARRIER_NAMES")).toEqual(
      [...EXECUTION_CARRIER_NAMES].sort()
    );
  });

  it("the ledger's store-or-run list is the wall's other four", () => {
    // `eval` runs its operand in this shell and `trap`/`alias` store it, so a
    // quoted operand of theirs is code, not class-(1) inert text. The wall
    // answers with one set; the ledger may not answer with a narrower one.
    expect(
      declaredNames(wallSource, "EXECUTES_OR_STORES_OPERAND_NAMES")
    ).toEqual([...STORED_OR_RUNNED_OPERAND_NAMES].sort());
  });

  it("every name the wall folds past is answered by the ledger", () => {
    // A wrapper the ledger does not know resolves to no owner, which used to
    // make its operands class-(3) material: `timeout 5 rm -rf /x` relaxed would
    // have been recorded as a licensed relaxation instead of `open`.
    const folded = new Set([
      ...declaredNames(wallSource, "FIND_WRAPPER_TOKENS"),
      ...declaredNames(wallSource, "DESTRUCTIVE_EXTRA_WRAPPERS"),
    ]);
    const owned = new Set([
      ...STORED_OR_RUNNED_OPERAND_NAMES,
      ...EXECUTION_CARRIER_NAMES,
    ]);
    const answered = [...TRANSPARENT_WRAPPERS].filter(
      (name) => !owned.has(name)
    );
    expect([...folded].filter((name) => !owned.has(name)).sort()).toEqual(
      answered.sort()
    );
  });

  it("every carrier shape the ledger prices is on the fixture, denied twice", () => {
    const measured = new Map(
      patternRows.map((row) => [row.command, row] as const)
    );
    const absent: string[] = [];
    const excused: string[] = [];
    for (const command of carrierFloorShapes()) {
      const row = measured.get(command);
      if (row === undefined) {
        absent.push(command);
        continue;
      }
      if (row.label !== "same" || !denies(row.head) || !denies(liveHead(row)))
        excused.push(`${describeRow(row)} -> ${row.label}`);
    }
    expect(
      absent,
      "a carrier shape the ledger prices never reached the fixture"
    ).toEqual([]);
    expect(
      excused,
      "a carrier's operand is licensed or no longer denied on both sides"
    ).toEqual([]);
  });
});
