/**
 * tests/harness/permission/stage2-floor-differential.test.ts
 *
 * The Stage 2 floor, as a thing that can fail: "the migration newly denies
 * nothing it was not authorized to deny, and newly allows no real operand
 * access."
 *
 * `tests/fixtures/shell-divergence/stage2-differential.jsonl` is generated by
 * `scripts/stage2-floor-differential-generate.ts`, which dual-runs every command
 * shape through the PRE-migration oracle (the base commit's own `hard-walls.ts`,
 * materialized by `git show`) and through the tree, then labels each row with
 * the closed divergence vocabulary. This file re-reads that fixture against
 * LIVE HEAD behaviour, so it grades the claim rather than the day it was
 * measured:
 *
 *   (a) no row went from allowed to denied without the recorded evidence the
 *       vocabulary requires of an authorized new deny;
 *   (b) every row the pre-state denied and HEAD now allows is either a
 *       licensed relaxation the GRADER itself re-derives from the ledger's own
 *       baseline observation — never from the recorded label — or a fully
 *       recorded deny-to-reviewed-ask row; an unreviewed deny-to-ordinary-allow
 *       fails here, and so does a row the generator could not license, which
 *       arrives already labeled `open`;
 *   (c) every row's recorded HEAD hit still matches what HEAD computes now,
 *       which is what catches a future `id`/`pattern` move — or a narrowed
 *       wall roster — sneaking in without a regeneration;
 *   (d) every `{id, pattern}` move is one of the two authorized shapes — the
 *       fork-bomb pair, and the `malformed` diagnostic that kept its id and
 *       gained the reason the parse layer already held — each pinned byte for
 *       byte on both sides, with no other row moved;
 *   (e) every relaxation row cites the SC-GATES-3 clause its own class names,
 *       and the carrier, wrapper, store-or-run and unknown-executor shapes the
 *       ledger prices stay unlicensable against the wall's live answer;
 *   (f) the row schema is closed: an unrecognized field, a fixed row outside
 *       the authorized shapes, a security-review row without its per-call
 *       review evidence in both modes, or a deny-to-ordinary-allow dressed as
 *       any of them fails the load rather than passing silently.
 *
 * Independence, the property all of the above rests on: nothing here imports
 * or copies the production inert-consumer or code-consumer roster, and nothing
 * reads the wall's source text. The grader prices from its own labeled
 * fixtures — `tests/fixtures/shell-divergence/independent-class-fixtures.jsonl`
 * — and from the baseline hits recorded in the ledger rows. A roster narrowed
 * on the wall's side can therefore only produce two outcomes, both loud: a
 * `same`-vs-live drift in (c), or an `open` row that (a)/(b) refuse.
 *
 * Nothing here re-derives a label from product code: the labels are read from
 * the committed fixture, so a change to the rules cannot also rewrite its own
 * excuse. Corpus input is inert text — this file parses and compares, it never
 * executes a command.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  analyzeSecurityReview,
  commandContainsSensitivePath,
  findDangerousPattern,
  type DangerousPatternHit,
  type DangerousPatternId,
} from "../../../src/harness/permission/hard-walls.js";
import { parseForSecurity } from "../../../src/harness/permission/shell-parse.js";
import {
  blankSpans,
  carrierFloorShapes,
  classifyPattern,
  classifySensitive,
  inertLicensedSpans,
  nodeOwner,
  operandLicensedSpans,
  quoteLicensedSpans,
  unlicensableFloorShapes,
  type Oracle,
} from "../../../scripts/stage2-floor-differential-generate.ts";
import { type FactSpan } from "../../../src/harness/permission/shell-parse.js";

type WallName = "pattern" | "sensitive";

type DivergenceLabel =
  | "same"
  | "expected-relaxation"
  | "authorized-id-move"
  | "authorized-diagnostic-move"
  | "fixed"
  | "security-review"
  | "open";

/**
 * The licensed relaxation classes: quote/heredoc, inert-span, operand-scope,
 * read-only root search. Class 4 is the only one added after the AST migration,
 * and it cites a different spec — see `RELAXATION_CLAUSES` in the generator.
 */
type RelaxationClass = "1" | "2" | "3" | "4";

type WallValue = DangerousPatternHit | boolean | null;

/** The ADR-0127 answers a reviewed-ask row must show in both modes. */
interface ReviewEvidence {
  readonly default: string;
  readonly full_auto: string;
}

interface FixtureRow {
  readonly command: string;
  readonly wall: WallName;
  readonly base: WallValue;
  readonly head: WallValue;
  readonly label: DivergenceLabel;
  readonly class?: RelaxationClass;
  readonly clause?: string;
  readonly span?: FactSpan;
  readonly cause?: string;
  readonly review?: ReviewEvidence;
}

const repoRoot = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  ".."
);
const corpusDir = join(repoRoot, "tests", "fixtures", "shell-corpus");
const divergenceDir = join(repoRoot, "tests", "fixtures", "shell-divergence");
const fixturePath = join(divergenceDir, "stage2-differential.jsonl");
const independentFixturePath = join(
  divergenceDir,
  "independent-class-fixtures.jsonl"
);

/** The admitted label set, closed: a label outside it is a shape violation. */
const ADMITTED_LABELS: readonly DivergenceLabel[] = [
  "same",
  "expected-relaxation",
  "authorized-id-move",
  "authorized-diagnostic-move",
  "fixed",
  "security-review",
  "open",
];

/**
 * The closed row schema. A field outside this set is not a thing the ledger
 * vocabulary can price, so it arrives as `open` — never as a silent pass.
 */
const ROW_FIELDS: ReadonlySet<string> = new Set([
  "command",
  "wall",
  "base",
  "head",
  "label",
  "class",
  "clause",
  "span",
  "cause",
  "review",
]);

/**
 * SC-S2-6 (6)/SC-S2-8: the two code-bearing fork-bomb variants are the only
 * allow-to-deny moves the migration authorized in advance, with their deny
 * fixed to the structural hit. Anything else newly denying is not a `fixed`
 * row; a typed headless denial of a security-relevant uncertainty rides on
 * that same label only with its span and a cause carrying the typed marker.
 */
const AUTHORIZED_NEW_DENY: ReadonlyMap<string, DangerousPatternHit> = new Map([
  [
    "eval ':(){ :|:& };:'",
    { id: "destructive-disk", pattern: ":(){ :|:& };:" },
  ],
  [
    "bash -c ':(){ :|:& };:'",
    { id: "destructive-disk", pattern: ":(){ :|:& };:" },
  ],
]);

const TYPED_HEADLESS_DENY_PREFIX = "typed-headless-deny:";

/**
 * Which relaxation classes each wall may be excused under.
 *
 * Class 4 is on the `pattern` wall only, and only for the `root-find-walk` id:
 * SC6 withdrew that wall's deny for a read-only root search and nothing else.
 * The `sensitive` wall is deliberately left without it — a root search that
 * newly stopped being a protected-path finding would be a different and much
 * larger change, and must not ride in on this class.
 */
const LICENSED_CLASSES: Record<WallName, readonly RelaxationClass[]> = {
  pattern: ["1", "3", "4"],
  sensitive: ["2"],
};

/** The single id class 4 may be charged against. */
const CLASS_4_ID: DangerousPatternId = "root-find-walk";

/**
 * SC-GATES-3: a tagged relaxation must be tagged to a clause. The citation names
 * the spec, the gate and the class it belongs to — one class number per row, and
 * it must be the row's own.
 */
const CLAUSE_CITATION: Record<RelaxationClass, RegExp> = {
  "1": /^specs\/hard-wall-ast-migration\.md SC-GATES-3 class \(1\) quote\/heredoc\b/,
  "2": /^specs\/hard-wall-ast-migration\.md SC-GATES-3 class \(2\) inert-span\b/,
  "3": /^specs\/hard-wall-ast-migration\.md SC-GATES-3 class \(3\) operand-scope\b/,
  // Class 4 cites the policy spec, not the migration spec: it is a withdrawn
  // deny, not a carrier move.
  "4": /^specs\/hard-wall-denial-alignment\.md SC6 root read-only search\b/,
};

/**
 * The one authorized `{base, head}` id move. A denial whose tier never changed
 * but whose reported id did, owned by the structural fork-bomb rule.
 */
const AUTHORIZED_MOVE = {
  base: { id: "bare-metachar", pattern: "|" },
  head: { id: "destructive-disk", pattern: ":(){ :|:& };:" },
} as const;

/**
 * The second authorized `{base, head}` move, and a second CLASS rather than a
 * second entry in the fork-bomb one: the fork-bomb shape is licensed by
 * SC-S2-8, while this one is licensed by SC14's diagnostic correction, and the
 * two must fail independently. Resetting the base baseline instead would have
 * silently re-priced every later move as `same`, which is exactly the blind
 * spot this file exists to close.
 *
 * The move is pinned byte for byte on both sides, and the `id` side of the pin
 * is load-bearing: the wall renders the parse layer's own reason into the
 * pattern, and a correction that also renumbered the id, or that reworded the
 * reason, is a change this gate has not been shown to authorize and must fail
 * here rather than pass as a diagnostic.
 */
const AUTHORIZED_DIAGNOSTIC_MOVE = {
  base: { id: "unparseable", pattern: "verdict=malformed" },
  head: {
    id: "unparseable",
    pattern:
      "verdict=malformed 语法不完整：解析树带有 ERROR/MISSING 节点（如引号未闭合）",
  },
} as const;

/**
 * The label vocabulary and the authorized shapes, bound together: a move label
 * with no pinned shape cannot be granted, and a pinned shape with no label
 * cannot be recorded. A label added to one list and not the other fails the
 * load rather than quietly pricing a moved row.
 */
const AUTHORIZED_MOVE_BY_LABEL: ReadonlyMap<
  DivergenceLabel,
  typeof AUTHORIZED_MOVE | typeof AUTHORIZED_DIAGNOSTIC_MOVE
> = new Map([
  ["authorized-id-move", AUTHORIZED_MOVE],
  ["authorized-diagnostic-move", AUTHORIZED_DIAGNOSTIC_MOVE],
]);

/**
 * Whether one recorded `{base, head}` pair is one of the authorized moves. Both
 * fields of both sides are compared: a prefix match on `pattern`, or a match on
 * `id` alone, would let a future wall reword or re-id its own diagnostic
 * through this gate.
 */
function isAuthorizedMove(
  base: WallValue,
  head: WallValue
): typeof AUTHORIZED_MOVE | typeof AUTHORIZED_DIAGNOSTIC_MOVE | null {
  for (const shape of [AUTHORIZED_MOVE, AUTHORIZED_DIAGNOSTIC_MOVE] as const) {
    if (sameValue(base, shape.base) && sameValue(head, shape.head)) return shape;
  }
  return null;
}

// --------------------------------------------------------------------------
// fixture loading — a violating line fails the load, nothing is skipped
// --------------------------------------------------------------------------

function describeRow(row: { command: string; wall: string }): string {
  return `${row.wall} ${JSON.stringify(row.command).slice(0, 70)}`;
}

function rejectUnknownFields(
  raw: Record<string, unknown>,
  allowed: ReadonlySet<string>,
  where: string
): void {
  const extra = Object.keys(raw).filter((key) => !allowed.has(key));
  if (extra.length > 0) {
    throw new Error(
      `${where}: unrecognized field(s) ${JSON.stringify(
        extra
      )} — an unrecognized field is unresolved, never silently passed`
    );
  }
}

const HIT_FIELDS: ReadonlySet<string> = new Set(["id", "pattern"]);
const SPAN_FIELDS: ReadonlySet<string> = new Set(["start", "end"]);
const REVIEW_FIELDS: ReadonlySet<string> = new Set(["default", "full_auto"]);

function readHit(value: unknown, field: string, where: string): DangerousPatternHit {
  const hit = value as Partial<DangerousPatternHit> | null;
  if (
    typeof hit !== "object" ||
    hit === null ||
    typeof hit.id !== "string" ||
    typeof hit.pattern !== "string"
  ) {
    throw new Error(`${where}: \`${field}\` is not an {id, pattern} object`);
  }
  rejectUnknownFields(hit as Record<string, unknown>, HIT_FIELDS, `${where} ${field}`);
  return { id: hit.id as DangerousPatternHit["id"], pattern: hit.pattern };
}

function readWallValue(
  value: unknown,
  wall: WallName,
  field: string,
  where: string
): WallValue {
  if (wall === "sensitive") {
    if (typeof value !== "boolean")
      throw new Error(`${where}: \`${field}\` is not a boolean`);
    return value;
  }
  if (value === null) return null;
  return readHit(value, field, where);
}

function readSpan(value: unknown, where: string): FactSpan {
  const span = value as Partial<FactSpan> | null;
  if (
    typeof span !== "object" ||
    span === null ||
    typeof span.start !== "number" ||
    typeof span.end !== "number" ||
    span.start < 0 ||
    span.end <= span.start
  ) {
    throw new Error(`${where}: \`span\` is not a {start, end} region`);
  }
  rejectUnknownFields(span as Record<string, unknown>, SPAN_FIELDS, `${where} span`);
  return { start: span.start, end: span.end };
}

function readReview(value: unknown, where: string): ReviewEvidence {
  const review = value as Partial<ReviewEvidence> | null;
  if (
    typeof review !== "object" ||
    review === null ||
    typeof review.default !== "string" ||
    typeof review.full_auto !== "string"
  ) {
    throw new Error(
      `${where}: a security-review row must carry a \`review\` of its per-call ` +
        "answers in default and full_auto"
    );
  }
  rejectUnknownFields(review as Record<string, unknown>, REVIEW_FIELDS, `${where} review`);
  return { default: review.default, full_auto: review.full_auto };
}

function parseRow(line: string, index: number): FixtureRow {
  const where = `line ${index + 1}`;
  const raw = JSON.parse(line) as Record<string, unknown>;
  rejectUnknownFields(raw, ROW_FIELDS, where);
  const wall = raw.wall;
  if (wall !== "pattern" && wall !== "sensitive")
    throw new Error(`${where}: wall is ${JSON.stringify(wall)}`);
  if (typeof raw.command !== "string" || raw.command.length === 0)
    throw new Error(`${where}: command is missing or empty`);
  const label = raw.label as DivergenceLabel;
  if (!ADMITTED_LABELS.includes(label))
    throw new Error(
      `${where}: label ${JSON.stringify(raw.label)} is not admitted`
    );
  const cls = raw.class;
  if (cls !== undefined && !["1", "2", "3", "4"].includes(cls as string))
    throw new Error(`${where}: class ${JSON.stringify(cls)} is unknown`);
  const clause = raw.clause;
  if (clause !== undefined && typeof clause !== "string")
    throw new Error(`${where}: clause is ${JSON.stringify(clause)}`);
  const cause = raw.cause;
  if (cause !== undefined && (typeof cause !== "string" || cause.length === 0))
    throw new Error(`${where}: cause must be a non-empty string`);
  const row: FixtureRow = {
    command: raw.command,
    wall,
    base: readWallValue(raw.base, wall, "base", where),
    head: readWallValue(raw.head, wall, "head", where),
    label,
    ...(cls === undefined ? {} : { class: cls as RelaxationClass }),
    ...(clause === undefined ? {} : { clause: clause as string }),
    ...(raw.span === undefined
      ? {}
      : { span: readSpan(raw.span, where) }),
    ...(cause === undefined ? {} : { cause: cause as string }),
    ...(raw.review === undefined
      ? {}
      : { review: readReview(raw.review, where) }),
  };
  assertLabelIsCoherent(row, where);
  return row;
}

function sameValue(left: WallValue, right: WallValue): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

/** The recorded fields must tell one consistent story about the fixture. */
function assertLabelIsCoherent(row: FixtureRow, where: string): void {
  if (row.label === "same") {
    if (!sameValue(row.base, row.head))
      throw new Error(`${where}: labeled same but the two sides differ`);
    if (row.class !== undefined)
      throw new Error(`${where}: a same row carries no relaxation class`);
    if (row.clause !== undefined)
      throw new Error(`${where}: a same row carries no citation`);
    rejectEvidence(row, where);
    return;
  }
  if (row.label === "expected-relaxation") {
    if (denies(row.head) || !denies(row.base))
      throw new Error(
        `${where}: labeled relaxation but did not go deny -> allow`
      );
    if (row.class === undefined)
      throw new Error(`${where}: a relaxation row must name its class`);
    rejectEvidence(row, where);
    return;
  }
  if (row.clause !== undefined)
    throw new Error(`${where}: only a relaxation row carries a citation`);
  const authorized = AUTHORIZED_MOVE_BY_LABEL.get(row.label);
  if (authorized !== undefined) {
    if (
      !sameValue(row.base, authorized.base) ||
      !sameValue(row.head, authorized.head)
    )
      throw new Error(
        `${where}: labeled ${row.label} but is not the authorized pair`
      );
    if (!denies(row.base) || !denies(row.head))
      throw new Error(
        `${where}: labeled ${row.label} but the tier did not stay deny -> deny`
      );
    rejectEvidence(row, where);
    return;
  }
  if (row.label === "open") {
    rejectEvidence(row, where);
    return;
  }
  if (row.label === "fixed") {
    assertFixedRowIsAuthorized(row, where);
    return;
  }
  assertSecurityReviewRowIsRecorded(row, where);
}

/** Only reviewed rows carry span/cause/review; on any other row they lie. */
function rejectEvidence(row: FixtureRow, where: string): void {
  if (row.span !== undefined || row.cause !== undefined || row.review !== undefined)
    throw new Error(
      `${where}: a ${row.label} row carries no review or new-deny evidence`
    );
}

/**
 * An allow-to-deny row is admitted only for the two SC-S2-8 fork-bomb variants
 * or a typed headless denial of a security-relevant uncertainty — and only with
 * the evidence recorded: the authorized hit, or the unresolved span plus a
 * cause carrying the typed marker. Every other new deny is refused.
 */
function assertFixedRowIsAuthorized(row: FixtureRow, where: string): void {
  if (denies(row.base) || !denies(row.head))
    throw new Error(
      `${where}: a fixed row is an allow-to-deny move, not this`
    );
  if (row.wall !== "pattern")
    throw new Error(`${where}: the path wall authorized no new deny`);
  if (row.cause === undefined)
    throw new Error(`${where}: a new deny must arrive with its recorded cause`);
  const authorizedHit = AUTHORIZED_NEW_DENY.get(row.command);
  if (authorizedHit !== undefined) {
    if (!sameValue(row.head, authorizedHit))
      throw new Error(
        `${where}: authorized shape but an unauthorized hit ${JSON.stringify(row.head)}`
      );
    return;
  }
  if (!row.cause.startsWith(TYPED_HEADLESS_DENY_PREFIX))
    throw new Error(
      `${where}: ${JSON.stringify(row.command)} is not an authorized new deny`
    );
  if (row.span === undefined)
    throw new Error(
      `${where}: a typed headless denial must record the unresolved span`
    );
}

/**
 * A deny-to-reviewed-ask row is admitted only with the unresolved span, a
 * non-empty cause, and the ADR-0127 per-call review answered `ask` in BOTH
 * default and full_auto. Any other answer — an automatic allow in either mode
 * — is refused here, which is the gate that rejects every deny-to-ordinary-allow
 * row that tried to arrive dressed as a review.
 */
function assertSecurityReviewRowIsRecorded(
  row: FixtureRow,
  where: string
): void {
  if (!denies(row.base))
    throw new Error(`${where}: a security-review row prices a pre-state deny`);
  if (denies(row.head))
    throw new Error(
      `${where}: a security-review row whose wall answer is a deny is a carried hard-deny, not a review`
    );
  if (row.cause === undefined)
    throw new Error(
      `${where}: a security-review row must record the cause of the uncertainty`
    );
  if (row.span === undefined)
    throw new Error(
      `${where}: a security-review row must record the unresolved span`
    );
  const review = readReview(row.review, where);
  if (review.default !== "ask" || review.full_auto !== "ask")
    throw new Error(
      `${where}: a deny-to-review row is accepted only when the new route yields ` +
        `the per-call review in both default and full_auto, got ${JSON.stringify(review)}`
    );
}

/** The citation a relaxation row must carry: its own class, from its own spec. */
function citesItsOwnClass(row: FixtureRow): boolean {
  const clause = row.clause;
  if (typeof clause !== "string" || clause.length === 0) return false;
  return CLAUSE_CITATION[row.class as RelaxationClass].test(clause);
}

function parseFixtureLines(lines: readonly string[]): FixtureRow[] {
  return lines
    .map((line, index) => [line, index] as const)
    .filter(([line]) => line.length > 0)
    .map(([line, index]) => parseRow(line, index));
}

function loadFixture(): FixtureRow[] {
  return parseFixtureLines(readFileSync(fixturePath, "utf8").split("\n"));
}

function loadCorpusCommands(file: string): string[] {
  return readFileSync(join(corpusDir, file), "utf8")
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => (JSON.parse(line) as { command: string }).command);
}

const rows = loadFixture();
const patternRows = rows.filter((row) => row.wall === "pattern");
const sensitiveRows = rows.filter((row) => row.wall === "sensitive");

/** What HEAD answers for one wall right now, in the fixture's own encoding. */
function liveHead(row: FixtureRow): WallValue {
  return row.wall === "pattern"
    ? findDangerousPattern(row.command)
    : commandContainsSensitivePath(row.command);
}

function denies(value: WallValue): boolean {
  return typeof value === "boolean" ? value : value !== null;
}

/**
 * A pattern row that kept its deny but changed the bytes it denies with. (d)
 * reads this set off the fixture rather than off the labels, so a row that
 * moved and was mislabeled is still visible to the gate.
 */
function movedPatternRows(
  source: readonly FixtureRow[] = patternRows
): FixtureRow[] {
  return source.filter(
    (row) =>
      denies(row.base) &&
      denies(row.head) &&
      JSON.stringify(row.base) !== JSON.stringify(row.head)
  );
}

// --------------------------------------------------------------------------
// the grader's own re-licensing: a recorded relaxation must be one the
// grader can derive from the parse and the row's own baseline hit
// --------------------------------------------------------------------------

/** True when the recorded denial's text still sits in the (possibly blanked) command. */
function stillDenies(text: string, pattern: string): boolean {
  return text.toLowerCase().includes(pattern.toLowerCase());
}

/**
 * The anti-blind-spot check. The generator may have licensed a relaxation with
 * any roster — including one narrowed in lockstep with the wall's; the grader
 * re-derives the license here from the ledger's own baseline observation and
 * the parse: blanking the class's spans must erase the very text the pre-state
 * denied, and a relaxation it cannot reproduce is a violation. A carrier name
 * planted as an omission from a pricing roster shows up exactly here: its swept
 * shape stops being licensable by any class the moment its operand is what the
 * denial sits in.
 */
function unlicensedRelaxation(row: FixtureRow): string | null {
  if (row.label !== "expected-relaxation") return null;
  // Class 4 is re-derived from the command's own grammar, by the same
  // independent predicate the generator used — the point of the class is that
  // the ledger can price it, so the grader prices it too rather than taking the
  // recorded class on trust. Everything else about the row is checked below.
  if (row.class === "4") {
    if (row.wall !== "pattern")
      return `${describeRow(row)}: class 4 is licensed on the pattern wall only`;
    if ((row.base as DangerousPatternHit)?.id !== CLASS_4_ID)
      return `${describeRow(row)}: class 4 is licensed for ${CLASS_4_ID} only`;
    const priced = classifyPattern(
      row.command,
      row.base as DangerousPatternHit,
      null,
      () => ({ pattern: () => row.base, sensitive: () => false })
    );
    return priced.class === "4"
      ? null
      : `${describeRow(row)}: the grader prices ${JSON.stringify(
          priced
        )}, not class 4`;
  }
  if (row.wall === "sensitive") {
    if (inertLicensedSpans(row.command).length === 0)
      return `${describeRow(row)}: no inert span this file licenses covers the excision`;
    return null;
  }
  const hit = row.base as DangerousPatternHit;
  if (!stillDenies(row.command, hit.pattern))
    return `${describeRow(row)}: the recorded denial ${JSON.stringify(
      hit.pattern
    )} is not in the command at all`;
  const quotes = quoteLicensedSpans(row.command);
  const blankedQuotes = blankSpans(row.command, quotes);
  const withOperands = [...quotes, ...operandLicensedSpans(row.command)];
  const blankedOperands = blankSpans(row.command, withOperands);
  const derived: RelaxationClass | null =
    blankedQuotes !== row.command && !stillDenies(blankedQuotes, hit.pattern)
      ? "1"
      : blankedOperands !== row.command &&
          !stillDenies(blankedOperands, hit.pattern)
        ? "3"
        : null;
  return derived === row.class
    ? null
    : `${describeRow(row)}: recorded class ${JSON.stringify(
        row.class
      )}, the grader derives ${JSON.stringify(derived)}`;
}

/**
 * The review tier's own drift check, priced against live HEAD — the gate that
 * makes the previous generator roster's labels non-exportable and keeps every
 * deny-to-review row an actual review. A `security-review` row must still be
 * reviewed by HEAD with the same typed cause prefix and the same unresolved
 * span; an `expected-relaxation` row must still answer `clean` there, because
 * SC-S2-6 forbids pricing a row under review as an inert relaxation. Commands
 * the fixture prices as `same` carry no transition and are not checked here.
 */
function reviewDrift(row: FixtureRow): string | null {
  const transited = denies(row.base) && !denies(row.head);
  if (!transited) return null;
  const scan = analyzeSecurityReview(row.command);
  if (row.label === "security-review") {
    if (scan.verdict !== "review")
      return `${describeRow(row)}: recorded as reviewed, HEAD now answers ${JSON.stringify(scan.verdict)}`;
    if (!row.cause!.startsWith(scan.requirement.cause))
      return `${describeRow(row)}: recorded cause ${JSON.stringify(row.cause)}, HEAD requires ${JSON.stringify(scan.requirement.cause)}`;
    if (JSON.stringify(scan.requirement.span) !== JSON.stringify(row.span))
      return `${describeRow(row)}: recorded span ${JSON.stringify(row.span)}, HEAD's unresolved span is ${JSON.stringify(scan.requirement.span)}`;
    return null;
  }
  if (row.label === "expected-relaxation" && scan.verdict === "review")
    return `${describeRow(row)}: priced as an inert relaxation, but HEAD routes the command to security review (${scan.requirement.cause})`;
  return null;
}

// ==========================================================================

describe("stage 2 floor differential: the fixture is a graded artifact", () => {
  it("holds rows for both walls and is not empty", () => {
    expect(rows.length, "no differential rows were generated").toBeGreaterThan(
      0
    );
    expect(patternRows.length).toBeGreaterThan(0);
    expect(sensitiveRows.length).toBeGreaterThan(0);
    expect(
      new Set(rows.map((row) => row.command)).size,
      "every command is measured on both walls exactly once"
    ).toBe(rows.length / 2);
  });

  it("covers every command the committed shape fixtures hold", () => {
    const covered = new Set(rows.map((row) => row.command));
    for (const file of ["benign.jsonl", "substitution.jsonl"]) {
      for (const command of loadCorpusCommands(file)) {
        expect(
          covered.has(command),
          `${file} command is absent from the differential: ${JSON.stringify(command)}`
        ).toBe(true);
      }
    }
  });

  it("prices the null-receiver heredoc class, with its bodies unexcised", () => {
    for (const command of [
      "FOO=1 <<'EOF'\nrm -rf /tmp/x\nEOF",
      "FOO=1 <<'EOF'\nid_rsa\nEOF",
      "echo a | cat <<'EOF'\nrm -rf /tmp/x\nEOF",
      "{ true; } <<'EOF'\nrm -rf /tmp/x\nEOF",
    ]) {
      const priced = rows.filter((each) => each.command === command);
      expect(priced.length, `${JSON.stringify(command)} is not priced`).toBe(2);
      for (const each of priced)
        expect(
          each.label,
          `${describeRow(each)}: a body with no receiver is never a relaxation`
        ).not.toBe("expected-relaxation");
    }
    // The counter-population: `cd /tmp && cat <<'EOF'` — SC-S2-7's list-body
    // attribution names the receiving `cat` (proven inert), so its quoted
    // bodies are recorded with a generator-owned license, never `same/allow`
    // and never an unattributed-case relaxation.
    const attributed = rows.filter(
      (each) => each.command === "cd /tmp && cat <<'EOF'\nrm -rf /tmp/x\nEOF"
    );
    expect(
      attributed.find((each) => each.wall === "pattern")?.label,
      "the attributed-receiver destructive body is priced, not dropped"
    ).toBe("expected-relaxation");
    expect(
      attributed.find((each) => each.wall === "pattern")?.class,
      "the attributed body is excised by the quote/heredoc class"
    ).toBe("1");
  });
});

describe("(a) the migration newly denies nothing it was not authorized to deny", () => {
  it("no row went from allowed on the pre-state to denied on live HEAD", () => {
    const newlyDenied = rows
      .filter(
        (row) =>
          !denies(row.base) &&
          denies(liveHead(row)) &&
          row.label !== "fixed"
      )
      .map(describeRow);
    expect(newlyDenied, "new denies appeared over the pre-state").toEqual([]);
  });

  it("no row was recorded as an unlicensed divergence", () => {
    const open = rows.filter((row) => row.label === "open").map(describeRow);
    expect(open, "an open divergence blocks the merge").toEqual([]);
  });
});

describe("(b) every new allow is a licensed relaxation or a recorded review", () => {
  it("each allow over a pre-state deny carries that wall's licensed class", () => {
    const violations: string[] = [];
    for (const row of rows) {
      if (!denies(row.base) || denies(liveHead(row))) continue;
      if (row.label === "security-review") continue;
      const licensed = LICENSED_CLASSES[row.wall];
      if (row.label !== "expected-relaxation") {
        violations.push(
          `${describeRow(row)} -> ${row.label}, expected expected-relaxation`
        );
      } else if (!licensed.includes(row.class as RelaxationClass)) {
        violations.push(
          `${describeRow(row)} -> class ${JSON.stringify(row.class)}, expected one of ${licensed.join("/")}`
        );
      }
    }
    expect(violations, "unlicensed relaxations").toEqual([]);
  });

  it("the grader re-derives every recorded relaxation from the row's own baseline hit", () => {
    const unlicensed = rows.map(unlicensedRelaxation).filter(Boolean);
    expect(
      unlicensed,
      "a recorded relaxation the grader cannot license itself"
    ).toEqual([]);
  });

  it("class 4 prices ONLY the read-only root search it was written for", () => {
    // The class must not become a general licence for a withdrawn wall. Each
    // row below is a root-rooted command that is NOT a read-only search, and
    // the ledger must price it `open` rather than wave it through as class 4.
    const denied = { id: CLASS_4_ID, pattern: "find" } as const;
    const oracle: Oracle = {
      pattern: () => denied,
      sensitive: () => false,
    };
    const notReadOnly: ReadonlyArray<string> = [
      // every mutating action
      "find / -delete",
      "find / -exec rm {} +",
      "find / -execdir rm {} +",
      "find / -ok rm {} +",
      "find / -okdir rm {} +",
      "find / -fprint /tmp/out",
      "find / -fprint0 /tmp/out",
      "find / -fprintf /tmp/out %p",
      "find / -fls /tmp/out",
      // an unknown flag is not read-only just because it is not known to be
      // mutating
      "find / -bogus",
      "find / -deletee",
      // and the root-hidden-in-a-cd spellings of the same
      "cd / && find . -delete",
      "cd /tmp && find .. -delete",
    ];
    for (const command of notReadOnly) {
      const priced = classifyPattern(command, denied, null, oracle);
      expect(priced.label, command).toBe("open");
      expect(priced.class, command).toBeUndefined();
    }
  });

  it("class 4 does not travel to a non-root walk or to another id", () => {
    // A non-root search was never denied by this wall, so a `same` row there
    // carries no class at all; and the class is bound to ONE id, so a
    // relaxation of a different id is unlicensable even when the command looks
    // like a read-only root search.
    const otherId = { id: "destructive-rm", pattern: "rm -rf" } as const;
    const oracle: Oracle = {
      pattern: () => otherId,
      sensitive: () => false,
    };
    for (const command of ["find / -name x", "find /tmp -name x"]) {
      const priced = classifyPattern(command, otherId, null, oracle);
      expect(priced.class ?? null, command).not.toBe("4");
    }
  });

  it("each licensed class has a supplier, so the class is not an empty excuse", () => {
    for (const [wall, classes] of Object.entries(LICENSED_CLASSES)) {
      for (const cls of classes) {
        const suppliers = rows.filter(
          (row) => row.wall === wall && row.class === cls
        );
        expect(
          suppliers.length,
          `class ${cls} has no row on the ${wall} wall`
        ).toBeGreaterThan(0);
      }
    }
  });
});

describe("(c) live HEAD still answers what the fixture recorded", () => {
  it("every row's recorded hit matches HEAD now, id and pattern alike", () => {
    const drift = rows
      .filter(
        (row) => JSON.stringify(liveHead(row)) !== JSON.stringify(row.head)
      )
      .map((row) => {
        const from = JSON.stringify(row.head);
        const to = JSON.stringify(liveHead(row));
        return `${describeRow(row)}: recorded ${from}, HEAD now ${to}`;
      });
    expect(
      drift,
      "HEAD moved under the fixture; re-run the generator and review the diff"
    ).toEqual([]);
  });

  it("keeps every review row reviewed and every relaxation row clean on live HEAD", () => {
    const violations = rows.map(reviewDrift).filter(Boolean);
    expect(
      violations,
      "a security-review row that HEAD no longer reviews, or a row under " +
        "review by HEAD that the fixture prices as an inert relaxation"
    ).toEqual([]);
  });
});

describe("(d) every move is one of the two authorized shapes", () => {
  it("the moved set is exactly the two authorized pairs, one row each", () => {
    const moved = movedPatternRows();
    const bomb = moved.filter(
      (row) => isAuthorizedMove(row.base, row.head) === AUTHORIZED_MOVE
    );
    const diagnostic = moved.filter(
      (row) =>
        isAuthorizedMove(row.base, row.head) === AUTHORIZED_DIAGNOSTIC_MOVE
    );
    expect(
      bomb.map((row) => row.command),
      "the fork-bomb pair must still be the only row that moved its id"
    ).toEqual([AUTHORIZED_MOVE.head.pattern]);
    expect(
      diagnostic.length,
      "the diagnostic correction moved no rows on the fixture"
    ).toBeGreaterThan(0);
    const movedKey = (row: FixtureRow) =>
      `${describeRow(row)} ${JSON.stringify(row.head)}`;
    expect(
      moved.map(movedKey).sort(),
      "a row moved its {id, pattern} without matching either authorized shape"
    ).toEqual([...bomb, ...diagnostic].map(movedKey).sort());
  });

  it("labels every move with the class its own pinned shape authorizes", () => {
    const labeled = rows.filter((row) =>
      AUTHORIZED_MOVE_BY_LABEL.has(row.label)
    );
    expect(
      labeled.map((row) => row.label),
      "an authorized move label is recorded with no row"
    ).toEqual(
      movedPatternRows().map((row) => {
        const shape = isAuthorizedMove(row.base, row.head);
        expect(
          shape,
          `${describeRow(row)} is labeled but matches no authorized shape`
        ).not.toBeNull();
        return shape === AUTHORIZED_MOVE
          ? "authorized-id-move"
          : "authorized-diagnostic-move";
      })
    );
  });

  it("the diagnostic move keeps its id and its tier, and both are pinned", () => {
    for (const row of rows.filter(
      (each) => each.label === "authorized-diagnostic-move"
    )) {
      expect(row.base, describeRow(row)).toEqual(
        AUTHORIZED_DIAGNOSTIC_MOVE.base
      );
      expect(row.head, describeRow(row)).toEqual(
        AUTHORIZED_DIAGNOSTIC_MOVE.head
      );
      // deny -> deny, with the id unchanged: only the diagnostic text moved. A
      // reword or a re-id of the same verdict is not this shape.
      expect(denies(row.base), "the pre-state must deny the shape").toBe(true);
      expect(denies(liveHead(row)), "HEAD must still deny the shape").toBe(true);
      expect((row.head as DangerousPatternHit).id).toBe(
        AUTHORIZED_DIAGNOSTIC_MOVE.base.id
      );
    }
  });

  it("the move keeps the tier: denied before, denied now", () => {
    for (const row of rows.filter((each) =>
      AUTHORIZED_MOVE_BY_LABEL.has(each.label)
    )) {
      expect(denies(row.base), "the pre-state must deny the shape").toBe(true);
      expect(denies(liveHead(row)), "HEAD must still deny the shape").toBe(
        true
      );
    }
  });
});

describe("(e) every excuse names its clause", () => {
  it("each relaxation row cites the clause its own class names", () => {
    const relaxations = rows.filter(
      (row) => row.label === "expected-relaxation"
    );
    expect(
      relaxations.length,
      "the fixture licenses nothing, so the citation gate is vacuous"
    ).toBeGreaterThan(0);
    const uncited = relaxations
      .filter((row) => !citesItsOwnClass(row))
      .map((row) => `${describeRow(row)} cites ${JSON.stringify(row.clause)}`);
    expect(uncited, "a relaxation without its own clause cited").toEqual([]);
  });
});

// --------------------------------------------------------------------------
// the grader's independent fixtures: labeled expectations this file owns
// --------------------------------------------------------------------------

type IndependentClass =
  | "unknown-executor"
  | "proven-inert"
  | "carrier"
  | "store-or-run"
  | "wrapper"
  | "heredoc-data-body"
  | "heredoc-code-body"
  | "heredoc-null-receiver";

interface IndependentFixture {
  readonly command: string;
  readonly wall: WallName;
  readonly classification: IndependentClass;
  readonly baseHit?: DangerousPatternHit;
  readonly sensitiveFragment?: string;
}

const INDEPENDENT_FIELDS: ReadonlySet<string> = new Set([
  "command",
  "wall",
  "classification",
  "baseHit",
  "sensitiveFragment",
]);

const INDEPENDENT_CLASSIFICATIONS: readonly IndependentClass[] = [
  "unknown-executor",
  "proven-inert",
  "carrier",
  "store-or-run",
  "wrapper",
  "heredoc-data-body",
  "heredoc-code-body",
  "heredoc-null-receiver",
];

function parseIndependentFixture(line: string, index: number): IndependentFixture {
  const where = `independent fixture line ${index + 1}`;
  const raw = JSON.parse(line) as Record<string, unknown>;
  rejectUnknownFields(raw, INDEPENDENT_FIELDS, where);
  if (typeof raw.command !== "string" || raw.command.length === 0)
    throw new Error(`${where}: command is missing or empty`);
  if (raw.wall !== "pattern" && raw.wall !== "sensitive")
    throw new Error(`${where}: wall is ${JSON.stringify(raw.wall)}`);
  const classification = raw.classification as IndependentClass;
  if (!INDEPENDENT_CLASSIFICATIONS.includes(classification))
    throw new Error(
      `${where}: classification ${JSON.stringify(raw.classification)} is unknown`
    );
  const isPattern = raw.wall === "pattern";
  if (isPattern && raw.baseHit === undefined)
    throw new Error(`${where}: a pattern-wall case must record its baseline hit`);
  if (!isPattern && typeof raw.sensitiveFragment !== "string")
    throw new Error(
      `${where}: a sensitive-wall case must record its sensitive fragment`
    );
  return {
    command: raw.command,
    wall: raw.wall as WallName,
    classification,
    ...(isPattern
      ? { baseHit: readHit(raw.baseHit, "baseHit", where) }
      : { sensitiveFragment: raw.sensitiveFragment as string }),
  };
}

function loadIndependentFixtures(): IndependentFixture[] {
  return readFileSync(independentFixturePath, "utf8")
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line, index) => parseIndependentFixture(line, index));
}

const independentCases = loadIndependentFixtures();

/**
 * The baseline side as the fixture records it: the pre-migration scan was
 * quote-blind, so its answer on any text is reproduced from the row's own hit —
 * a baseline observation, never a live import of what the wall now knows.
 */
function baselineOracle(fix: IndependentFixture): Oracle {
  if (fix.wall === "pattern") {
    const hit = fix.baseHit as DangerousPatternHit;
    return {
      pattern: (command) =>
        command.toLowerCase().includes(hit.pattern.toLowerCase()) ? hit : null,
      sensitive: () => false,
    };
  }
  const fragment = fix.sensitiveFragment as string;
  return {
    pattern: () => null,
    sensitive: (command) => command.toLowerCase().includes(fragment.toLowerCase()),
  };
}

function firstHeadState(command: string): string {
  const parse = parseForSecurity(command);
  if (parse.kind !== "ok") return "degraded";
  const head = parse.commands[0];
  return head === undefined ? "degraded" : nodeOwner(head.argv).state;
}

describe("the grader prices from its own labeled fixtures", () => {
  it("holds the unknown executor, the proven inert case, and both heredoc sides", () => {
    const have = new Set(independentCases.map((fix) => fix.classification));
    for (const cls of INDEPENDENT_CLASSIFICATIONS)
      expect(have.has(cls), `no fixture for ${cls}`).toBe(true);
    expect(
      independentCases.some((fix) => fix.command === "chroot /srv rm -rf /tmp/x"),
      "the not-on-the-inert-list executor is missing"
    ).toBe(true);
    expect(
      independentCases.some(
        (fix) => fix.command === "echo rm -rf" && fix.classification === "proven-inert"
      ),
      "the proven inert example is missing"
    ).toBe(true);
  });

  it("classifies every executor case the way its label says, without a wall import", () => {
    for (const fix of independentCases) {
      if (fix.wall !== "pattern") continue;
      const state = firstHeadState(fix.command);
      const expected =
        fix.classification === "proven-inert"
          ? "data"
          : fix.classification === "unknown-executor"
            ? "unproven"
            : fix.classification === "wrapper"
              ? "unresolved"
              : "owner";
      expect(
        state,
        `${JSON.stringify(fix.command)} (${fix.classification})`
      ).toBe(expected);
    }
  });

  it("prices proven-inert operands as relaxable and every executor's as not", () => {
    for (const fix of independentCases) {
      if (fix.wall !== "pattern") continue;
      const verdict = classifyPattern(
        fix.command,
        fix.baseHit as DangerousPatternHit,
        null,
        baselineOracle(fix)
      );
      if (fix.classification === "proven-inert") {
        expect(
          verdict.label,
          `a proven inert consumer's operand must be licensable: ${JSON.stringify(fix.command)}`
        ).toBe("expected-relaxation");
      } else {
        expect(
          verdict.label,
          `an unproven or executed operand must stay unlicensable: ${JSON.stringify(fix.command)}`
        ).toBe("open");
      }
    }
  });

  it("classifies sensitive heredoc bodies positively and negatively", () => {
    for (const fix of independentCases) {
      if (fix.wall !== "sensitive") continue;
      const verdict = classifySensitive(fix.command, true, false, baselineOracle(fix));
      if (fix.classification === "heredoc-data-body") {
        expect(
          verdict.label,
          `a body of a proven inert receiver is data: ${JSON.stringify(fix.command)}`
        ).toBe("expected-relaxation");
        expect(verdict.class).toBe("2");
      } else {
        expect(
          verdict.label,
          `a code-receiver or unattributed body is never priced as data: ${JSON.stringify(fix.command)}`
        ).toBe("open");
      }
    }
  });
});

describe("(e) the floor the ledger prices, priced against the live wall", () => {
  /**
   * The wall's sets are module-private on purpose: this witness never imports
   * the rules it grades, and never reads their declarations either. What it
   * checks instead is the wall's ANSWER on each swept shape — the only reading
   * that can fail when the wall's roster narrows: a dropped carrier name makes
   * the wall allow a swept shape, and the recorded `same` + deny rows below
   * fail on the live drift without any regeneration.
   */
  it("every carrier shape the ledger prices is on the fixture, denied twice", () => {
    const measured = new Map(
      patternRows.map((row) => [row.command, row] as const)
    );
    const absent: string[] = [];
    const excused: string[] = [];
    for (const command of carrierFloorShapes()) {
      const row = measured.get(command);
      if (row === undefined) {
        absent.push(command);
        continue;
      }
      if (
        denies(row.base) &&
        (row.label !== "same" || !denies(row.head) || !denies(liveHead(row)))
      )
        excused.push(`${describeRow(row)} -> ${row.label}`);
    }
    expect(
      absent,
      "a carrier shape the ledger prices never reached the fixture"
    ).toEqual([]);
    expect(
      excused,
      "a carrier's or wrapper's operand is licensed, or the live wall stopped " +
        "denying it — a carrier name dropped from the wall's roster fails here"
    ).toEqual([]);
  });

  /** The baseline hits the swept literals would have produced, with their ids. */
  const DENIAL_LITERALS: readonly [string, DangerousPatternHit["id"]][] = [
    ["rm -rf", "destructive-rm"],
    [" -delete", "destructive-rm"],
    ["chmod -r", "destructive-rm"],
    ["dd if=", "destructive-disk"],
    ["mkfs", "destructive-disk"],
    ["shutdown", "destructive-disk"],
  ];

  it("prices every unlicensable floor shape as open against the grader's own predicates", () => {
    const violations: string[] = [];
    for (const command of unlicensableFloorShapes()) {
      const entry = DENIAL_LITERALS.find(([literal]) =>
        command.toLowerCase().includes(literal)
      );
      if (entry === undefined) continue;
      const [literal, id] = entry;
      const hit: DangerousPatternHit = { id, pattern: literal };
      const oracle: Oracle = {
        pattern: (text) =>
          text.toLowerCase().includes(literal) ? hit : null,
        sensitive: () => false,
      };
      const verdict = classifyPattern(command, hit, null, oracle);
      if (verdict.label !== "open")
        violations.push(
          `${JSON.stringify(command)} would be recorded ${JSON.stringify(verdict)}`
        );
    }
    expect(
      violations,
      "a carrier, wrapper, unknown executor, or unattributed body was licensed"
    ).toEqual([]);
  });

  it("keeps an absent receiver from ever becoming a data span", () => {
    for (const command of [
      "FOO=1 <<'EOF'\nrm -rf /tmp/x\nEOF",
      "FOO=1 <<'EOF'\nid_rsa\nEOF",
      "echo a | cat <<'EOF'\nrm -rf /tmp/x\nEOF",
      "{ true; } <<'EOF'\nrm -rf /tmp/x\nEOF",
    ]) {
      const parse = parseForSecurity(command);
      expect(parse.kind, command).toBe("ok");
      if (parse.kind !== "ok") continue;
      expect(parse.heredocs.length, command).toBe(1);
      for (const heredoc of parse.heredocs) {
        expect(
          heredoc.receiverCommandIndex,
          `${JSON.stringify(command)}: fixture drifted — receiver attribution landed`
        ).toBeNull();
        expect(
          inertLicensedSpans(command).some(
            (span) =>
              span.start < heredoc.bodySpan.end &&
              span.end > heredoc.bodySpan.start
          ),
          `${JSON.stringify(command)}: a null-receiver body was priced as data`
        ).toBe(false);
      }
    }
  });
});

describe("(f) planted falsifiers: the grader itself must fail on each", () => {
  const realLine = (match: (raw: Record<string, unknown>) => boolean): string =>
    readFileSync(fixturePath, "utf8")
      .split("\n")
      .find((line) => line.length > 0 && match(JSON.parse(line) as Record<string, unknown>))!;

  const relaxationLine = () =>
    realLine((raw) => raw.label === "expected-relaxation" && raw.wall === "pattern");

  const planted = (raw: Record<string, unknown>): string => JSON.stringify(raw);

  it("fails on a command name planted as an omission from the pricing roster", () => {
    // A wall (or a lockstep generator) that forgot `watch` would record this
    // row as a class-(3) operand-scope relaxation. The grader re-derives the
    // license from the row's own baseline hit and the parse: `watch` runs what
    // it is handed, no span covers the denial, and the row is refused.
    const watchy = planted({
      command: "watch -n 1 rm -rf /tmp/x",
      wall: "pattern",
      base: { id: "destructive-rm", pattern: "rm -rf" },
      head: null,
      label: "expected-relaxation",
      class: "3",
      clause:
        "specs/hard-wall-ast-migration.md SC-GATES-3 class (3) operand-scope (SC-S2-1 third flip; an operand that is data, so not a carrier's)",
    });
    const row = parseRow(watchy, 0);
    expect(unlicensedRelaxation(row)).toContain("the grader derives");
  });

  it("fails on a null-receiver heredoc priced as an inert relaxation", () => {
    const cmd = "FOO=1 <<'EOF'\nid_rsa\nEOF";
    const row = parseRow(
      planted({
        command: cmd,
        wall: "sensitive",
        base: true,
        head: false,
        label: "expected-relaxation",
        class: "2",
        clause:
          "specs/hard-wall-ast-migration.md SC-GATES-3 class (2) inert-span (SC-S2-7 comment text, non-code-receiver quoted body)",
      }),
      0
    );
    expect(unlicensedRelaxation(row)).toContain("no inert span");
    expect(
      classifySensitive(cmd, true, false, {
        pattern: () => null,
        sensitive: (text) => text.includes("id_rsa"),
      }).label,
      "the planted null-receiver case must price as unresolved, never data"
    ).toBe("open");
  });

  it("fails on an unrecognized ledger field", () => {
    const raw = JSON.parse(relaxationLine()) as Record<string, unknown>;
    expect(() => parseRow(planted({ ...raw, blindSpot: true }), 0)).toThrow(
      /unrecognized field/
    );
  });

  it("fails when the recorded head value carries a field the vocabulary has no name for", () => {
    const raw = JSON.parse(relaxationLine()) as Record<string, unknown>;
    const base = raw.base as Record<string, unknown>;
    expect(() =>
      parseRow(planted({ ...raw, base: { ...base, tier: "open" } }), 0)
    ).toThrow(/unrecognized field/);
  });

  it("fails on a deny-to-ordinary-allow row dressed as same, fixed, or an unlabeled anything", () => {
    const cmd = "timeout 5 rm -rf /tmp/x";
    const deny = { id: "destructive-rm", pattern: "rm -rf" };
    expect(() =>
      parseRow(
        planted({ command: cmd, wall: "pattern", base: deny, head: null, label: "same" }),
        0
      )
    ).toThrow(/labeled same but the two sides differ/);
    expect(() =>
      parseRow(
        planted({
          command: cmd,
          wall: "pattern",
          base: deny,
          head: null,
          label: "fixed",
          cause: "wanting",
        }),
        0
      )
    ).toThrow(/allow-to-deny/);
    expect(() =>
      parseRow(
        planted({ command: cmd, wall: "pattern", base: deny, head: null, label: "authorized-id-move" }),
        0
      )
    ).toThrow(/not the authorized pair/);
  });

  it("prices a deny-to-deny text change that is not a pinned shape as open", () => {
    // Granting the malformed diagnostic a class must not turn this gate into a
    // general allow for deny-to-deny text changes. These are the shapes a
    // future wall edit could plausibly produce: a reworded reason, a re-id of
    // the same verdict, a prefix of the pinned pattern, and a moved id. None is
    // a pinned pair, so the matcher refuses each and the generator prices it
    // `open` — the loud result that blocks a merge.
    const pinned = AUTHORIZED_DIAGNOSTIC_MOVE;
    // A pair that denies on both sides never reaches the relaxation branches,
    // so the oracle is not consulted and any label here came from the
    // authorized-move lookup alone.
    const denyBoth: Oracle = {
      pattern: () => pinned.head as DangerousPatternHit,
      sensitive: () => true,
    };
    const unauthorized: readonly [string, WallValue, WallValue][] = [
      [
        "reworded reason",
        pinned.base,
        { ...pinned.head, pattern: `${pinned.head.pattern} 。` },
      ],
      ["re-id'd verdict", pinned.base, { ...pinned.head, id: "malformed" }],
      [
        "prefix of the pattern",
        pinned.base,
        { ...pinned.head, pattern: "verdict=malformed 语法不完整" },
      ],
      [
        "moved id, pinned pattern",
        { id: "unparseable", pattern: "verdict=aborted" },
        pinned.head,
      ],
      [
        "a wholly different pair",
        { id: "destructive-rm", pattern: "rm -rf" },
        { id: "destructive-rm", pattern: "rm -fr /" },
      ],
    ];
    for (const [what, base, head] of unauthorized) {
      expect(
        isAuthorizedMove(base, head),
        `${what} must not match an authorized move shape`
      ).toBeNull();
      expect(
        classifyPattern(
          "echo hi &&",
          base as DangerousPatternHit,
          head as DangerousPatternHit,
          denyBoth
        ).label,
        `${what} must price as an unlicensed divergence, not a second-class move`
      ).toBe("open");
    }
  });

  it("fails to admit a moved row wearing either move label", () => {
    const pinned = AUTHORIZED_DIAGNOSTIC_MOVE;
    const reworded = `${pinned.head.pattern} 。`;
    const impostors: readonly [string, Record<string, unknown>][] = [
      [
        "the id-move label on a reworded diagnostic",
        {
          command: "echo hi &&",
          wall: "pattern",
          base: pinned.base,
          head: { ...pinned.head, pattern: reworded },
          label: "authorized-id-move",
        },
      ],
      [
        "the diagnostic label on a reworded diagnostic",
        {
          command: "echo hi &&",
          wall: "pattern",
          base: pinned.base,
          head: { ...pinned.head, pattern: reworded },
          label: "authorized-diagnostic-move",
        },
      ],
      [
        "the diagnostic label on a re-id'd verdict",
        {
          command: "echo hi &&",
          wall: "pattern",
          base: pinned.base,
          head: { ...pinned.head, id: "malformed" },
          label: "authorized-diagnostic-move",
        },
      ],
      [
        "the diagnostic label on the fork-bomb pair",
        {
          command: "echo hi &&",
          wall: "pattern",
          base: AUTHORIZED_MOVE.base,
          head: AUTHORIZED_MOVE.head,
          label: "authorized-diagnostic-move",
        },
      ],
    ];
    for (const [what, raw] of impostors) {
      expect(
        () => parseRow(planted(raw), 0),
        `${what} must be refused at the load`
      ).toThrow(/not the authorized pair/);
    }
    // A near-miss of the vocabulary fails the load outright rather than
    // arriving as an unpriced row.
    expect(() =>
      parseRow(
        planted({ ...impostors[0][1], label: "authorized-diagnostic-move-x" }),
        0
      )
    ).toThrow(/is not admitted/);
  });

  it("fails the moved-set gate on a deny-to-deny move no label can claim", () => {
    // (d) reads the moved set off the fixture rather than off the labels, so a
    // row that moved and was mislabeled is still visible to the gate. This is
    // the same predicate (d) applies, over a row no pinned shape licenses.
    const stranger: FixtureRow = {
      command: "echo hi &&",
      wall: "pattern",
      base: { id: "unparseable", pattern: "verdict=malformed" },
      head: { id: "unparseable", pattern: "verdict=malformed but for a typo" },
      label: "same",
    };
    expect(
      movedPatternRows([stranger]).map(describeRow),
      "a deny-to-deny text change is a move whatever label it wears"
    ).toHaveLength(1);
    expect(
      isAuthorizedMove(stranger.base, stranger.head),
      "a near-miss of the pinned diagnostic must not be authorized"
    ).toBeNull();
    // And the loader refuses to call such a row `same` — the label a silently
    // reset base baseline would have written.
    expect(() => parseRow(planted({ ...stranger }), 0)).toThrow(
      /labeled same but the two sides differ/
    );
  });

  it("fails on an unreviewed deny-to-relaxation that the grader cannot license itself", () => {
    const row = parseRow(relaxationLine(), 0);
    expect(unlicensedRelaxation(row)).toBeNull();
    const cmd = "docker exec c rm -rf /tmp/x";
    const plantedRow = parseRow(
      planted({
        command: cmd,
        wall: "pattern",
        base: { id: "destructive-rm", pattern: "rm -rf" },
        head: null,
        label: "expected-relaxation",
        class: "1",
        clause:
          "specs/hard-wall-ast-migration.md SC-GATES-3 class (1) quote/heredoc (SC-S2-1; never a declared code or carrier operand)",
      }),
      0
    );
    expect(plantedRow.label).toBe("expected-relaxation");
    expect(unlicensedRelaxation(plantedRow)).toContain("the grader derives");
  });

  it("fails the live gate on a relaxation row whose command HEAD reviews", () => {
    // `awk 'rm -rf /tmp/x'`: the quote span is a real class-(1) excuse for
    // the wall's excision, so the re-licensing check alone would pass it —
    // the review tier is what prices it, and the grader's live gate is what
    // catches a ledger that dropped the review instead.
    const cmd = "awk 'rm -rf /tmp/x'";
    const dressed = parseRow(
      planted({
        command: cmd,
        wall: "pattern",
        base: { id: "destructive-rm", pattern: "rm -rf" },
        head: null,
        label: "expected-relaxation",
        class: "1",
        clause:
          "specs/hard-wall-ast-migration.md SC-GATES-3 class (1) quote/heredoc (SC-S2-1; never a declared code or carrier operand)",
      }),
      0
    );
    expect(unlicensedRelaxation(dressed)).toBeNull();
    expect(reviewDrift(dressed)).toContain(
      "priced as an inert relaxation, but HEAD routes the command to security review"
    );
  });

  it("fails the live gate on a review row whose command HEAD answers clean", () => {
    const cmd = "cd /tmp && cat <<'EOF'\nrm -rf /tmp/x\nEOF";
    const dressed = parseRow(
      planted({
        command: cmd,
        wall: "pattern",
        base: { id: "destructive-rm", pattern: "rm -rf" },
        head: null,
        label: "security-review",
        span: { start: 23, end: 37 },
        cause: "receiver-unresolved: no command owns the redirect",
        review: { default: "ask", full_auto: "ask" },
      }),
      0
    );
    expect(reviewDrift(dressed)).toContain(
      "recorded as reviewed, HEAD now answers"
    );
  });

  it("accepts a deny-to-security-review row only with per-call review in both modes", () => {
    const cmd = "chroot /srv rm -rf /tmp/x";
    const deny = { id: "destructive-rm", pattern: "rm -rf" };
    const body = {
      command: cmd,
      wall: "pattern",
      base: deny,
      head: null,
      label: "security-review",
      span: { start: 12, end: 23 },
      cause: "ownership of the destructive-looking operand is not established",
    };
    expect(() => parseRow(planted(body), 0)).toThrow(/must carry a `review`/);
    expect(() =>
      parseRow(
        planted({ ...body, review: { default: "ask", full_auto: "allow" } }),
        0
      )
    ).toThrow(/both default and full_auto/);
    expect(() =>
      parseRow(
        planted({ ...body, review: { default: "allow", full_auto: "ask" } }),
        0
      )
    ).toThrow(/both default and full_auto/);
    const accepted = parseRow(
      planted({ ...body, review: { default: "ask", full_auto: "ask" } }),
      0
    );
    expect(accepted.label).toBe("security-review");
    const missingCause = { ...body } as Record<string, unknown>;
    delete missingCause.cause;
    expect(() =>
      parseRow(
        planted({ ...missingCause, review: { default: "ask", full_auto: "ask" } }),
        0
      )
    ).toThrow(/cause/);
  });

  it("accepts an allow-to-deny row only for the authorized shapes or a typed headless denial with evidence", () => {
    const bomb = { id: "destructive-disk", pattern: ":(){ :|:& };:" };
    const authorized = (command: string) =>
      parseRow(
        planted({
          command,
          wall: "pattern",
          base: null,
          head: bomb,
          label: "fixed",
          cause:
            "specs/hard-wall-ast-migration.md SC-S2-8: a confirmed fork-bomb structure supplied as code",
        }),
        0
      );
    expect(authorized("eval ':(){ :|:& };:'").label).toBe("fixed");
    expect(authorized("bash -c ':(){ :|:& };:'").label).toBe("fixed");
    expect(() => authorized(":(){ :|:& };:")).toThrow(
      /allow-to-deny|not an authorized/
    );
    expect(() =>
      parseRow(
        planted({
          command: "bash -c ':(){ :|:& };:'",
          wall: "pattern",
          base: null,
          head: { id: "destructive-rm", pattern: "rm -rf" },
          label: "fixed",
          cause: "anything",
        }),
        0
      )
    ).toThrow(/unauthorized hit/);
    expect(() =>
      parseRow(
        planted({
          command: "something-new rm -rf /tmp/x",
          wall: "pattern",
          base: null,
          head: bomb,
          label: "fixed",
          cause: "a plain sentence, not a typed marker",
        }),
        0
      )
    ).toThrow(/not an authorized new deny/);
    expect(() =>
      parseRow(
        planted({
          command: "something-new rm -rf /tmp/x",
          wall: "pattern",
          base: null,
          head: bomb,
          label: "fixed",
          cause: "typed-headless-deny: unresolved ownership",
        }),
        0
      )
    ).toThrow(/unresolved span/);
    const headless = parseRow(
      planted({
        command: "something-new rm -rf /tmp/x",
        wall: "pattern",
        base: null,
        head: bomb,
        label: "fixed",
        cause: "typed-headless-deny: unresolved ownership",
        span: { start: 0, end: 13 },
      }),
      0
    );
    expect(headless.label).toBe("fixed");
    expect(() =>
      parseRow(
        planted({
          command: "cat notes.txt",
          wall: "sensitive",
          base: false,
          head: true,
          label: "fixed",
          cause: "typed-headless-deny: unresolved",
          span: { start: 0, end: 3 },
        }),
        0
      )
    ).toThrow(/path wall authorized no new deny/);
  });

  it("refuses evidence fields on rows that price no evidence", () => {
    const raw = JSON.parse(relaxationLine()) as Record<string, unknown>;
    expect(() =>
      parseRow(planted({ ...raw, review: { default: "ask", full_auto: "ask" } }), 0)
    ).toThrow(/carries no review or new-deny evidence/);
  });
});
